### ISSUE TITLE
GPL Exception

### ISSUE THREAD

**Issue by urras** [irungentoo/toxcore#1064]
In order to publish [Antidote](https://github.com/dvor/Antidote) in the Apple app store and Test Flight, Toxcore needs to make a GPL exception. However, we need permission to add an exception from the following people who have contributed to Toxcore:

- [ ] @mannol
- [ ] @irungentoo
- [ ] @aitjcize 
- [ ] @FullName
- [ ] @Martijnvdc
- [ ] @tycho
- [ ] @stal888
- [ ] @tux3
- [ ] @notsecure
- [ ] @cgar
- [ ] @nurupo
- [ ] @maksqwe
- [ ] @JFreegman
- [ ] @czarkoff
- [ ] @saneki
- [ ] @schuetzm
- [ ] @K0K0
- [ ] @redwire
- [ ] @tylerb
- [ ] @Jman012
- [ ] @pyruvate
- [ ] @jin-eld
- [ ] @exonity
- [ ] @palistov
- [ ] @lobiCode
- [ ] @Bahkuh
- [ ] @BtbN
- [ ] @kc1212
- [ ] @Ansa89
- [ ] @Garydos
- [ ] @kyconny
- [ ] @dubslow

The exception can be viewed [here](https://gist.githubusercontent.com/urras/16e5e9a67016f3c30ac0/raw)
If you hereby agree to these changes, say so in this thread.

**Comment by wiseoldman95** [comment]
Dr. RMS has some replies, he did not sign them yet. I will include the signatured as soon as I obtain them.
__________________________

@irungentoo 

  > Tox won't be relicensed.

  > What will happen is that all the contributers to toxcore will agree to a
  > fancy agreement that will basically say that they allow their
  > contributions to be distributed on the apple store under certain conditio=
  > ns

That is very interesting.  Could someone directly involved please send
me mail about this so I can learn more?

One possibility this offers is to make the concession for a limited
period of time.

It is important to release the source code and tell people how to
install it on a jailbroken iThing.  Even if most iThing users install
the program from the crapp store, the release of that same version as
free software is necessary so that you won't be distributing
proprietary software.

__________________________
@ennui-games 
  > I've been following Tox's development with interest and even installed
  > it on a few machines myself. I think that tactically submitting to
  > apple's restrictions is a poor move. 

  >  I don't believe you can meaningfully protest apple's
  > restrictions while accepting them, and what you agree to now might not
  > be what you agree to next year, or even ten years from now.

This is the crucial point.  By making a deal today, with few users,
Tox would get a worse deal than it could hope to get in the future
with more users.  If you make permanent concessions at an early stage,
when you are small, that means later when you get big and have strength
you can't use it.

Tox would also forfeit the opportunity it has now to put pressure on
Apple:

  > Right now you have the opportunity
  > to publicize the reasons why Tox cannot be submitted to their appstore.
  > While Tim Cook is addressing their WWDC about apple's strides to protect
  > user privacy this is could be extremely inflammatory (and potentially
  > very newsworthy).

I don't think Apple would make concessions out of desire to get Tox
alone onto the iThings.  But Tox may not be alone.  Its resistance
could inspire other projects to resist as well.  There's one clear
path to building up enough pressure to make Apple give ground, and
that's by building up resistance project by project.

Meanwhile, what would Tox get from giving in to Apple?  Not much.  As
has been pointed out, users of iThings are a minority that don't value
freedom very much.  Not a lot of users would come from there.

If someone says, "I can't talk with you using Tox until it runs on my
iPhone," you can respond, "Android phones are cheap."  Or even, "Let
me give you a phone with Replicant."

**Comment by dfortner** [comment]
Giving away people's freedom only to have it on the Apple Store? Really? LOL
I thought Tox was about the users and now you are going to sell them just to get a plce on the Apple Store?

**Comment by linktoming** [comment]
Nice read. I think this article is also relevant.
http://www.tuaw.com/2011/01/09/the-gpl-the-app-store-and-you/

**Comment by GrayHatter** [comment]
@irungentoo close as wontfix?

There's NO way to get an consensus at this point, so any actual options should go into a new issue.

**Comment by dvor** [comment]
Hello everyone,

Sorry for bothering with this issue again, just wanted to share licensing model of libsignal.

Currently the status of [Antidote](https://github.com/Antidote-for-Tox/Antidote) is following - Antidote is licensed under MIT, which violates GPL license of toxcore. ~ a year ago or so we made a verbal agreement somewhere on IRC that toxcore developers won't complain about license violation unless Antidote will become evil. Actually I'm not sure if irungentoo remembers that agreement :-)

Now back to libsignal. They've updated their license recently and I think that it is a really nice example which toxcore can follow:

https://github.com/whispersystems/libsignal-protocol-c#license
> License
> 
> Copyright 2015-2016 Open Whisper Systems
> 
> Licensed under the GPLv3: http://www.gnu.org/licenses/gpl-3.0.html
> 
> Additional Permissions For Submission to Apple App Store: Provided that you are otherwise in compliance with the GPLv3 for each covered work you convey (including without limitation making the Corresponding Source available in compliance with Section 6 of the GPLv3), Open Whisper Systems also grants you the additional permission to convey through the Apple App Store non-source executable versions of the Program as incorporated into each applicable covered work as Executable Versions only under the Mozilla Public License version 2.0 (https://www.mozilla.org/en-US/MPL/2.0/).

Also see their blog post about license update https://whispersystems.org/blog/license-update/

**Comment by GrayHatter** [comment]
The GPL doesn't limit your ablitiy to licence antidote how ever you'd like. Just once compiled with toxcore, you must also make the source available with a GPL version as well.

The problem in this thread is that there are too many people with contrubtions to toxcore that we can't get in contact with to get permission for a 2nd licence.

**Comment by dvor** [comment]
Shall we at least try? There are [42 people](https://github.com/irungentoo/toxcore/graphs/contributors?from=2013-06-23&to=2016-10-06&type=a) who have added more than 100 lines of code. 32 from them have some activity in their GitHub profile for past few month.

**Comment by askmatey** [comment]
Tactically submitting to apple's oppressive restrictions is not only a *poor move*, it's bullshit. Point. And if you think it is safe to use tox on iThings, you must be lipstick wearing schmendrick. An contradictio in adiecto. End of story.

**Comment by GrayHatter** [comment]
@dvor we can try, but I'd put money on >1 of them not being willing to.

Also, it'd be better to use the current commit only, and then, only with files ending in .c or .h They're the only ones that would still be able to do harm.

**Comment by askmatey** [comment]
Tactically submitting to apple's oppressive restrictions is not only a *poor move*, it's bullshit. Point.

**Comment by GrayHatter** [comment]
@askmatey care to expand on that thought? Or is your goal simply to throw flame?

**Comment by GrayHatter** [comment]
For anyone interested, from my Toxcore HEAD => https://gist.github.com/GrayHatter/f9cbdd81623edd2c5b40473448937093

**Comment by GrayHatter** [comment]
And another by lines of code "owned" => https://gist.github.com/GrayHatter/8205f00b7a489667fc12c095bc49b99f

**Comment by rodneyrod** [comment]
I mean, the nuclear option would be to have a separate branch with all code who's owners agree to allow a license change, removing the code that can't be transferred and then slowly start working on replacing the missing components.

It's effective, though time consuming, and unfortunately those who are more passionate in the community would see this as an attempt to undermine their own exaggerated, purist view of copyleft.
