### ISSUE TITLE
Consider moving this repo to Tox organization on Github

### ISSUE THREAD

**Issue by krieger-od** [irungentoo/toxcore#1162]
It looks inconsistent that core lib is not amongst repos of Tox organization.

**Comment by dfortner** [comment]
@irungentoo said on IRC that he won't do that because he fears the Tox Foundation members may do a coup d'état or something.
My question: why does he fear his own organization? Sounds fishy to me. Everything should be under /tox, unless there's something really eerie going around. I wouldn't trust Tox until it starts working like a real organization and putting everything under /Tox github.

**Comment by ArchangeGabriel** [comment]
If some people where wanting to do a coup d’état, they can just fork the project anyway. This is a principle of OSS. So this is indeed a problem in project organization/management.

**Comment by irungentoo** [comment]
It's because it makes things easier for me.

Torvalds does it with and I don't see people complaining about it.

**Comment by ArchangeGabriel** [comment]
Can you tell us why it makes things easier for you (at least give some example)? I’m just curious, because I’ve been managing Bumblebee for a while, and we only had advantages to move everything to the Project organization rather than individual repos. And in fact, we even started by forking the project that was lying at @MrMEEE / because we where having too much problems with the fact it was under @MrMEEE.

And Linus is Linus, they are many people which are not satisfied of the authoritative way he is running Linux, but forking Linux or going against Linus is not worth it.

**Comment by krieger-od** [comment]
> Torvalds does it
Does what exactly?

> I don't see people complaining about it
Whatever you refer to as "it", is that an excuse to ignore people complaining about inconsistence in _your_ project?

**Comment by JFreegman** [comment]
@krieger-od No one is being ignored. Your question was answered and your complaint has been taken into consideration.

**Comment by dfortner** [comment]
> Your question was answered and your complaint has been taken into consideration.

Are you by any chance a bot that gives this vague answer to everyone? LOL

Is your argument for keeping this under a personal repo instead of Tox's one that "Linus does it too"?
A programmer, that supposedly deals with logic should know that's an argumentum ad populum (search that term). Also, answer @ArchangeGabriel
> Can you tell us why it makes things easier for you (at least give some example)?

**Comment by toxic-environment** [comment]
On https://github.com/irungentoo/toxcore/issues/1229 @irungentoo said: 

> This repo is my repo, not the Tox foundation repo. Go take your bullshit concerns somewhere else.

I think that answers everything.
Also, I'm a friend of @dfortner and he said he was banned from posting on this repository, that's why I'm here letting you guys know about this.

Looks like the Tox Foundation leaders (irungentoo and stqism) are enforcing censorship.

**Comment by irungentoo** [comment]
@toxic-environment This repo isn't for free speech. It's for getting work done.

**Comment by suhr** [comment]
@irungentoo, why don't you create a special place for dramas? This way anyone will be happy: repo belongs to development and tox project discussions goes to the tox project discussions place.

**Comment by irungentoo** [comment]
@suhr https://github.com/Tox/Tox-Foundation-Discussion/issues

**Comment by LapFox** [comment]
@irungentoo Probably a good idea to post that in the other locked issues too. If possible it might be a good idea to move those issues into that repository (is that even possible?).
