### ISSUE TITLE
Audio is extremely laggy in groupchats with >20 users

### ISSUE THREAD

**Issue by suhr** [irungentoo/toxcore#1170]
Subj.

**Comment by GrayHatter** [comment]
expected behavior, also new toxav on friday

**Comment by zetok** [comment]
@GrayHatter is this an expected behaviour for all the years of development to come?

**Comment by GrayHatter** [comment]
yup, the number will just jump. 

I'll likely leave an issues open if there was a great description of how to duplicate the issue, what the criteria for closing would look like. But a simple issue like this one of "Hey, trying to send audio to a lot of people takes a lot of bandwidth, and is laggy when you don't have enough!" I get to respond with, "Yeah, we know, get Google fiber!"

**Comment by zetok** [comment]
@GrayHatter so you're basically saying that toxcore will remain broken?

**Comment by GrayHatter** [comment]
Yup, if you consider broken that you can't stream audio to an arbitrarily large number of people broken... Personally I go with bandwidth is still constrained by the laws of physics, and toxcore has no plans to rewrite the physical constants of the universe...

**Comment by quininer** [comment]
Perhaps can let distribute audio between peer, and not just rely on the sender's broadband (like bittorrent). The sender needs to audio signatures to prevent tampering.

**Comment by GrayHatter** [comment]
@quininer the torrent protocol isn't designed for real time, or anything where the order of delivery matters. But we're looking into other similar options for AV in new groupchats...

**Comment by zetok** [comment]
>But we're looking into other similar options for AV in new groupchats...

Looking into them does not constitute being successful. Until there is a **merged** implementation that you mitigate the problem with smaller audio groupchats, IMHO issue should remain open.

**Comment by quininer** [comment]
@GrayHatter  You're right, bittorrent is more suitable for groupchat file. There is no central server is really difficult to do, You should probably marked as impossible to solve the issue.

**Comment by GrayHatter** [comment]
not impossible, just not a toxcore issue.  If you can show me an implementation that works, then it's a toxcore issue. Or if it was required for toxcore to function, then it'd be a toxcore issue. And I'm sure there's a lot of other things that could make this a toxcore issue. But no one else in the world of VoIP has managed to solve this yet. So until I'm convinced, that there's a way to solve this programmatically without just throwing more bandwidth at it... I'm going to say "It works, just throw more bandwidth at it..."

**Comment by quininer** [comment]
@GrayHatter I mean, you should not simply turn it off. This will make people think that the problem had been solved.

**Comment by GrayHatter** [comment]
All the no one else commenting or bumping this issue in a year? What ever will they do?

**Comment by zetok** [comment]
> If you can show me an implementation that works, then it's a toxcore issue.

…

>Or if it was required for toxcore to function, then it'd be a toxcore issue.

It is required.

>But no one else in the world of VoIP has managed to solve this yet.

And no one before Tox has made an easy, secure IM.

Is your point that Tox should stop innovation and start saying "hurr, durr, no one has made that, it's impossible" ?

>So until I'm convinced, that there's a way to solve this programmatically without just throwing more bandwidth at it... I'm going to say "It works, just throw more bandwidth at it..."

What part is the bandwidth? Were you unable to reproduce when each peer had sufficient bandwidth?

**Comment by GrayHatter** [comment]
Sneakernet is still the faster transfer method when trying to move vast amounts of data. Trying to push audio to large groups won't happen if you have a low throughput connection... It's expected that there will be lag, and delays when you're trying to push more data than you have the bandwidth for. 

> It is required.

Then you'll need more bandwidth... that or you're welcome to open a PR... Hell, even an issue that's more descriptive than "subj."

> And no one before Tox has made an easy, secure IM.

> Is your point that Tox should stop innovation and start saying "hurr, durr, no one has made that, it's impossible" ?

No I'm saying that we need to keep realistic expectations for a secure communications platform. Saying Toxcore can't magically create perfect compression algorithms, or that the reality distortion field that is toxcore doesn't increase my bandwidth isn't rational and/or reasonable. 

And even if you think it is, a new system and API for AV is coming, and then shortly after that new Groupchats API so then this issue REALLY will be irrelevant. 

I've locked it because now that we've all gotten so far off topic it's worthless as an issue. If you can still duplicate this problem after ToxAV gets merged tomorrow, you're welcome to open a new issue. But it needs to be way better than this one is...
