### ISSUE TITLE
bai

### ISSUE THREAD

**Issue by notadecent** [irungentoo/toxcore#1186]
Hello folks,
Just wanted to note I might not get back here again. I have been here since the beginning of the project and have seen lots of stuff happening, have met lots of neat developers too. Though I haven't been active the last few months, I've decided to leave this project as I don't feel like anymore. The reason being mostly the organization of the project.
I experienced the atmosphere being completely polluted. In the beginning there was lots of potential and lots of hype around, especially on 4chan, but this gradually turned into a place which drew away developers. So has someone come into the project who has acclaimed himself a high position and got away with it. Well, making mistakes is humanly, but this person has been making fouls consecutively in a manner which I think he has abused his rank for either sabotaging the project or placing himself on a very high horse. We had the security canary which died (due to understandable mistake,) absolutely inefficient GSoC mentorate, strangled ideas by derailing significant discussions in several IRC-channels, and the worst of all is the way this person communicates. There have been times where this person was not able to fulfill his tasks properly, blaming himself while he was the one who initiated these tasks, which have also been brought up and suggested by others. But he refused to co-operate. Until you point out this person is at fault, he bends the discussion in a way in which he makes himself irresponsible and becomes very supportive.
This could've been prevented in many ways, as there were people from outside and inside who tried to stop this train of guided misfortune, but there were again developers who resisted and did not want to comply.
Instead, the person in question is still sitting where he still stood and the project has remained relatively still, moving at snail's pace, relying momentarily mostly on exterior factors for their future path. I am not implying this person is the cause this dilemma, but also the fact that important stuff such as transparency came in lately, is one of the causes of why this project is crumbled in my eyes.
Hereby I want to say goodbye and thanks to those who have contributed, I have lost all my interest and have no hope left whatsoever for this project. Most of my ideas and stuff I'd maintained might also be dropped as I highly doubt the current politica will show interest in.

**Comment by dfortner** [comment]
Too bad all developers are leaving.
@notsecure 
@Proplex 
@notadecent 
@mahkoh
@landswellsong and @henotba
etc.

Looks like the tox foundation (composed by irungentoo and stqism only?) should rethink its actions or just close down. This isn't working, obviously.

**Comment by anubiann00b** [comment]
That's a pretty big overstatement. And with FOSS developers often come and go.

**Comment by dcharles525** [comment]
Wow, I didn't realize they all left. I still love the idea of Tox, I think the biggest issue is lack of a organized hierarchy, like lots of open source projects, but I hope to see Tox continue to grow! Tox4Lyfe

**Comment by urras** [comment]
Actually, mahkoh, landswellsong, and henotba never really left. 
landswellsong and henotba were GSoC students, so when GSoC ended, the majority of their contributions ended (however, they still contribute from time to time). Mahkoh still actively works on the Rust wrapper for Tox.

**Comment by stqism** [comment]
@urras You forgot to mention notsecure, a GSoC student who left after GSoC for school. 

Though at this point I'm just feeding the troll.

**Comment by landswellsong** [comment]
I'd like to point out that while my contribution is shitty and modest at best, I'm rather "trying do deal with overwhelming IRL problems". I know this sounds pathetic on my part (and it really is somewhat given my recent life events), but it's all like my own problems and not the lack of anything in Tox itself. I really hope I can manage to digest everything and get back on track.

**Comment by aaannndddyyy** [comment]
Best wishes to you, @landswellsong !!! May better times come!

**Comment by dfortner** [comment]
@urras
But henotba (alnf) has zero lines of code contributed according to https://github.com/irungentoo/toxcore/graphs/contributors
What the hell?
Also, weren't GSoC students supposed to keep continue contributing after the programme was over?
Where's @alnf @notsecure @ollieh @jhn1291 ?
I really can't think otherwise that Tox as an organization is a huge failure. I really wished it was better, but there's no hope.

**Comment by urras** [comment]
@dfortner The majority of her work was done in her repository at https://github.com/alnf/toxcore, until she stopped for personal reasons. As for the others, people often contribute code once or twice to a project, and then they move on to something else. Considering how vocal you are on this issue (as you have expressed your concern over this on at least 13 other Tox issues), I thought you would have known this by now.

**Comment by Astonex** [comment]
@dfortner is clearly an NSA agent sent to spread fear and doubt amongst promising security projects.

**Comment by dfortner** [comment]
@urras 
I don't see ***any*** line from alnf's repository merged into the master here. It's as if all her work was ignored? It looks like irungentoo implemented new group chats himself and threw her work into the trash. Why is that? And you should know better.

@Astonex 
Sorry, but calling others "NSA agents" instead of properly answering their concerns is really unprofessional. Even more in a project filled with doubts like Tox. Damn, just look at this issue we are posting on! notadecent, part of the official Tox Organization left and gave many reasons as to why he did so. Still you think there's nothing wrong and all concerns people raise are fake and everyone is a spy?
 How about you check my account? It's been up since April 2013 and I have many good issues opened  on hundreads of projects, as well as countless pull-requests. Don't be so arrogant as to think Tox is perfect and anyone raising doubts about it are "NSA agents". This only makes me raise even more concerns about it and the unprofessionalism of the Tox Foundation. I guess notadecent's concerns were right, after all.

**Comment by mannol** [comment]
@dfortner The reason why nobody wants to answer to your concerns is that we are all too deep in this emotionally. Such questions stress us and bring up fresh wounds... It's hard to even say this but you see, @alnf died two months ago when those evil, Putin supported, devil guided, russians attacked peaceful Ukrainians even though they were under "cease fire". So it shattered my heart, and so many other developers hearts to heard that our beloved Alina who couldn't stand shit from nobody got blown in pieces by misguided, poorly programmed, BM-21 Grad so called "missiles". It was her dream to be a part of Tox Foundation as is, the Foundation which accepted her so kindly and full heartedly, and contribute to the one, true, repository that is irungentoo/toxcore.

So I beg you, please, understand our situation and don't even think we could ever ignore her work as it will stay in our hearts for the eternity, may she RIP in Peace...
Thank you.

**Comment by dfortner** [comment]
@mannol 
> alnf died two months ago
Her latest activity was less than 1 month ago https://github.com/alnf?tab=activity
Why would you lie about this?
Pretending someone is death instead of taking responsibility for a failed GSoC programme is dirty, I expected more from Tox Foundation members, since they claim to be so professional, privacy-caring and whatnot.

**Comment by mannol** [comment]
OH MY GOD SHE'S ALIVE!!! IT'S A MIRACLE I TELL YOU!

**Comment by aaannndddyyy** [comment]
@mannol : This is NOT funny. Please show some more respect.

**Comment by stqism** [comment]
@dfortner 
>I don't see any line from alnf's repository merged into the master here.

We try not to break master by merging things till being worked on. 

>It's as if all her work was ignored? It looks like irungentoo implemented new group chats himself and threw her work into the trash

Please stop putting words in people's mouths and jumping to conclusions, it's very unprofessional and creates the same childish name calling you got mad at @astonex for. 

>instead of taking responsibility for a failed GSoC programme is dirty

She didn't actually fail, GSoC is about encouraging the next generation of students to get in to and start contributing to open source, Tox or not. Not every students code is ready to be merged with every project, a common trait with GSoC projects with the Free Software Foundation and Freebsd Foundation. 

Next note, you seem to know a lot about the project in a lot of aspects but coincidentally forget details in your replies where you've only said bad things about the project. You can see how someone like @astonex would suspect you of being a NSA agent after one of the snowden leaks revealed that they are actually using clever disinformation tactics like that.

**Comment by alnf** [comment]
R.I.P.

**Comment by hexafluoride** [comment]
R.I.P.

**Comment by mannol** [comment]
R.I.P.

**Comment by Astonex** [comment]
R.I.P.

**Comment by stqism** [comment]
R.I.P.

**Comment by JFreegman** [comment]
@alnf need help pls respond

**Comment by mannol** [comment]
@JFreegman she can't... she kill... she rip...

**Comment by stal888** [comment]
![rip](https://cloud.githubusercontent.com/assets/774591/5793861/540501ee-9f09-11e4-99dd-21b1e5aeb46b.jpg)

**Comment by JFreegman** [comment]
@mannol we will have to summon her spirit then

**Comment by TheLastProject** [comment]
@dfortner I think the project is doing pretty fine. Yes, sometimes people disappear, but that is basically just part of the culture. I do understand your worries, but feel they are mostly ungrounded. Rest assured, the project does take the OP's notes seriously, even if it seems like they don't.

Also, please don't take the death and NSA jokes personally. It's kinda part of Tox' culture. See it as an inside-joke that has grown a bit large. I do thoroughly understand that our culture comes across as weird to those that don't hang around the community much, but rest assured, as someone closer to the community, things aren't nearly as bad as they seem.

**Comment by dubslow** [comment]
R.I.P.

**Comment by urras** [comment]
rip in pepperoni

**Comment by mannol** [comment]
@dfortner don't take @TheLastProject seriously. She a >she...

> she

**Comment by urras** [comment]
@mannol really pls chill

**Comment by codedust** [comment]
@TheLastProject Thanks for the explanation! ;D
I was a bit confused when the "R.I.P. mails" started to pollute my inbox.
Weired culture. ;)

**Comment by subliun** [comment]
@alnf seriously though please come on IRC

PS RIP

**Comment by dfortner** [comment]
@stqism 
> We try not to break master by merging things still being worked on.

Once GSoC was over and alnf was gone, irungentoo started working on the group chat reimplementation himself instead of merging her work and finishing it up. And don't come with this "breaking master" argument because that was exactly what irungentoo. Here's some proof from the time it happened: https://github.com/irungentoo/toxcore/issues/1087
Are you unaware of what's going on your own project? Or giving weak excuses to justify your made-up story? In either case, this is horrible.

> Please stop putting words in people's mouths and jumping to conclusions

When did I put words in someone's mouth? You are the one doing that right now, actually.

> it's very unprofessional

First of all, I don't need to be "professional" since I don't represent an organization, like you (and others in this thread) do. Still, I behave in a more respectful and thoughtful way then you do. Which is really off-putting...

> and creates the same childish name calling you got mad at @astonex for

I am a random person concerned with the situation going on and making proper comments, while developers spam the thread with unrelated stuff and made-up tales. Still, I'm the one being childish and name calling others? Good to know you are all this self-inserted in your "culture" that you start misunderstanding the real world... Re-read the thread, please.

> a common trait with GSoC projects with the Free Software Foundation and Freebsd Foundation.

It's "FreeBSD", not "Freebsd". Just a friendly tip so you don't make this mistake again.

@TheLastProject
> sometimes people disappear, but that is basically just part of the culture

So you would summarize your "culture" as hit-and-run or something like that? I don't get what you mean with this.

> Rest assured, the project does take the OP's notes seriously, even if it seems like they don't
Why not be more coherent and make your ideals the same as your appearance? Sounds like a big messy contradiction to appear to be something you are not. You take OP's notes seriously, but at the same time makes jokes, spam the thread and don't address any point? Something's really wrong here.

> Also, please don't take the death and NSA jokes personally. It's kinda part of Tox' culture.
So it's okay to call anyone worried about Tox an "NSA agent" and pretend people who stopped contributing are dead? Damn, this really is a toxic environment. I guess it can't be helped, though.

**Comment by mannol** [comment]
@dfortner That is NOT funny. Please show some respect.

**Comment by stal888** [comment]
@dfortner That is NOT funny. Please show some respect.

**Comment by dfortner** [comment]
@mannol @stal888 
Where exactly were I disrespectful?
Re-read my post, please.

**Comment by stal888** [comment]
@dfortner The word "t*xic" is triggering for some people (myself included). I would like to ask that you refrain from using that word because it could cause a relapse of my panic seizures.

**Comment by dubslow** [comment]
There's a lot of people here who have and continue to contribute to Tox, who are also acting incredibly unprofessionally because they don't represent any professional organization. stqism is basically the only one doing that, and he's plenty professional.

**Comment by dfortner** [comment]
@dubslow 
These are the people that represent the Tox Foundation: https://github.com/orgs/Tox/people
It's not only stqism. And even if it was, he also joined the others at the unprofessional, childish, "R.I.P." spam wave.

**Comment by stqism** [comment]
@dfortner 
>Once GSoC was over and alnf was gone, irungentoo started working on the group chat reimplementation himself instead of merging her work and finishing it up.

That is factually incorrect, @irungentoo started working on TCP group chats because @alnf didn't get fully how TCP works and needed something to go off of. He actually started before GSoC was over as a way of working together.

The rest of your paragraph is just blatant libel. (a published false statement that is damaging to a person's reputation; a written defamation.)

>I am a random person concerned with the situation going on and making proper comments, while developers spam the thread with unrelated stuff and made-up tales. Still, I'm the one being childish and name calling others? Good to know you are all this self-inserted in your "culture" that you start misunderstanding the real world... Re-read the thread, please.

Please stop attributing people having fun on their own as official representation of the project, people are free to act and behave on their own as they feel without needing to be policed.

**Comment by mannol** [comment]
@dfortner 

>So you would summarize your "culture" as hit-and-run or something like that?

are you making fun of our dear @alnf (RIP)? She didn't choose to get hit so you better apologize!

**Comment by stqism** [comment]
@dfortner 
>@dubslow 
>These are the people that represent the Tox Foundation: https://github.com/orgs/Tox/people
It's not only stqism. And even if it was, he also joined the others at the unprofessional, childish, "R.I.P." spam wave.

I updated my R.I.P. post to have a (These views represent me personally and not the project/Foundation)

**Comment by alnf** [comment]
Due to some circumstances I was unable to produce any code recently. I'm going to continue contributing to tox since now.
I'm really grateful for all your warm responses. I'm resting in peace now.
@JFreegman could you pls check your email.

**Comment by dfortner** [comment]
@stqism 

> That is factually incorrect

No, it isn't. Here's the proof irungentoo started reimplementing group chats from scratch, ignoring alnf's work and breaking group chats completely for around a week. #1087

> @irungentoo started working on TCP group chats because @alnf didn't get fully how TCP works and needed something to go off of

But why has irungentoo reimplemented group chats from scratch instead of taking alnf's work and starting from there? Her work hasn't been used at all. Still, you insist there's some noble reason behind this or whatever. There simply isn't.

> He actually started before GSoC was over as a way of working together.

Really? Show me a commit she did, then. All her work has been on her self-contained, completely ignored since GSoC, repository. And irungentoo didn't pulled anything there either.

> The rest of your paragraph is just blatant libel

How so? Address each point that is "blatant libel", please.

> Please stop attributing people having fun on their own as official representation of the project

Then remove them from https://github.com/orgs/Tox/people
Otherwise it's only natural to consider their words as those of the Tox Foundation itself. Specially when they post on a Tox issue thread, dammi.

**Comment by Astonex** [comment]
@dfortner I called you out as an NSA agent because all of your comments on Tox issues are attacking the Tox Foundation rather than talking about the actual issues at hand. You seem to have an agenda against Tox.

Also, just because people contribute to the Tox project does not mean they are actual members of the Tox Foundation. Anyone can commit code to an open-source project, some do so more than others. They can come and go as they wish.

Lastly, if you read the GSoC website, it is explicitly stated that organisations are under no obligation to use any of the code produced by students should they not wish to.

**Comment by ArchangeGabriel** [comment]
I don’t know what most of your people are doing there, but I think this is not the place for it. There exist IRC for discussion, or 4chan and r/circlejerk to do useless things.

Irrelevant things on GitHub and notifications spam like that is the best way to get people leaving your project.

I personally think Tox could be a very great and important project for the coming years, but you would want to kill it you wouldn’t act differently. They are a lot of concerns to be worked on in this project, even if @dfortner way of just throwing them away on developers is not the best way to remind you they exist, so if you have spare time, which I unfortunately have not, please look at them.

And share your culture somewhere else appropriate.

**Comment by dfortner** [comment]
@Astonex 

> your comments on Tox issues are attacking the Tox Foundation rather than talking about the actual issues at hand

Do you think issues with an organization aren't issues with the project the organization holds? That's really narrow-minded, in my opinion.
If an organization uses donated money unethically, for example, that's just as huge of an issue as a programming mistake.

> just because people contribute to the Tox project does not mean they are actual members of the Tox Foundation. Anyone can commit code to an open-source project, some do so more than others.

I'm not talking about any contributor that ever pulled a line of code, I'm talking about the people listed as members on the official page of the Tox Organization github page: https://github.com/orgs/Tox/people
Check the comments of those here in the thread.

> They can come and go as they wish

Of course they can, but when many of them go away like notadecent and notsecure did, raising issues about the Tox Foundation on their way out, things start to get shady. I, personally, lost my faith on the project because of this (as well as other things not to be discussed on this thread).

> Lastly, if you read the GSoC website, it is explicitly stated that organisations are under no obligation to use any of the code produced by students should they not wish to

I never implied alnf's code *had* to be used. What I said was that her code, as well as landswellsong's and jhn1291's weren't used and that such a thing makes me think GSoC was a failure.
And no student has contributed anything after GSoC ended. At least alnf's showed up and said she'll give it a go in the future. Still, sounds far from a success as the developers try to sell.

**Comment by Astonex** [comment]
>Do you think issues with an organization aren't issues with the project the organization holds?

You are well entitled to express these views however attacking the foundation in every issue is not how you should do it and raises questions about your motives. You should be discussing the exact issue at hand. If you have issues about the foundation you can come to IRC, open a new specific issue, email us etc. etc.

As for money there is a transparency page on https://donate.tox.im/

>I, personally, lost my faith on the project because of this 

Then why are you still here

>And no student has contributed anything after GSoC ended

Because they are students and need to focus on their work. I'm a student too and fully appreciate how much time university work can take up.

**Comment by opensourcewunder** [comment]
@dfortner Don't bother commenting on any more Tox issues. We're not interested in your kind. Go play with Ubuntu or something. Clearly a privacy-respecting user-friendly messenger is not for you.

Oh, and quit whining about members of the Tox Foundation. Just because you're some sour, tired, humourless Salaryman doesn't mean WE want to have OUR culture smashed up by some idiot invader crying about our jokes.

**Comment by opensourcewunder** [comment]
@ArchangeGabriel You should also stop whining at Tox developers and go play with Bleep or Telegram or some other kike messenger.

**Comment by ArchangeGabriel** [comment]
Great. We were just missing that newly created account inappropriate comment.

**Comment by urras** [comment]
@irungentoo seriously fam can we lock this issue?

**Comment by dfortner** [comment]
@stqism 

> however attacking the foundation in every issue is not how you should do it and raises questions about your motives

I don't "attack" the foundation in every issue, pal. I just raised concerns I had and, instead of answers, I got a spam wave. The responses I did get were shady, to say the least, such as that of stqism.

> You should be discussing the exact issue at hand
The "issue at hand" I pointed out is basically that the Foundation isn't professional or ethical from many people's point of view and that lots of members, such as notadecent, notsecure and Proplex left because of the messy and opaque "Tox Foundation".

**Comment by subliun** [comment]
@irungentoo and please remove the inappropriate comments

**Comment by stal888** [comment]
Can you remove the word "in*****priate" from your comment please? Or tag it with a trigger warning. Thanks

**Comment by Astonex** [comment]
@dfortner 
>The "issue at hand" I pointed out is basically that the Foundation isn't professional or ethical

Who cares. Focus on the code and well how the software works. No time for this bullshit.

**Comment by nurupo** [comment]
@dfortner 
>I never implied alnf's code had to be used. What I said was that her code, as well as landswellsong's and jhn1291's weren't used and that such a thing makes me think GSoC was a failure.

Well, our first GSoC wasn't really as great as we expected, but we are going to take this experience into account when the next GSoC comes. Speaking of the groupchats written by @alnf  and @landswellsong specifically -- the groupchats weren't fully completed and required some work and testing. @mannol and @JFreegman are currently working on improving @alnf's  and @landswellsong's groupchats to be merged into toxcore, so their code isn't really lost ( https://github.com/JFreegman/toxcore/tree/new_groupchats ).

**Comment by dfortner** [comment]
@Astonex 
> Who cares

I think many, if not most, people care about the behaviour of the Tox Foundation. Nobody wants to support, financially or otherwise, an unethical organization.

**Comment by stqism** [comment]
@dfortner
that is the definition of libel, you're not showing actual proof to your claims and rephrasing the same arguments by ignoring certain facts in your replies. 

Please address replies that directly contradict your own replies in order to encourage a civilized and factual discussion.

**Comment by dfortner** [comment]
@stqism 
You said alnf's work wasn't merged because you try not to break master. (no proof provided)
I said that wasn't the true reason. (proof: #1087 and https://github.com/irungentoo/toxcore/commit/d67624bf99d03ecb754a5f406a971ad41de1cd04 )

If someone's rephrasing the same arguments by ignoring certain facts, it's you.

**Comment by nurupo** [comment]
@dfortner
>Still, stqism made up a false reason for her work not being used here: #1186 (comment)

>We try not to break master

Please read my comment with a little bit more attention. I did say that their groupchats weren't complete and tested. Something incomplete and not tested would break master.

**Comment by dfortner** [comment]
@nurupo 
I'll try rephrasing that.
stqism made up a false reason (avoiding to break master) for her work not being used, however, that reason was clearly made-up since at the end of GSoC irungentoo broke master for his own re-implementation of groupchats that completely ignored alnf's work.

**Comment by opensourcewunder** [comment]
@DFoRTNeR stfu about 'ethics' we are al;l programmers here not ethicians

**Comment by subliun** [comment]
@dfortner Just out of interest, did you once go by the name of "neeh" in the #tox IRC channel?

**Comment by dfortner** [comment]
@subliun
I don't go to IRC and I don't see how's that relevant to this thread.

**Comment by opensourcewunder** [comment]
@subliun it's obvious that @dFARTner is either an NSA agent or niao/aois. maybe he's even sti. whoever he is he should shut up about things he doesn't understand (like Tox developer politics)

**Comment by nurupo** [comment]
@dfortner 
It's very possible that he was confident that his changes wouldn't break master. It's not like he would deliberately break his own project just for kicks of it after all. Not sure why you are assuming that he broke master deliberately.

**Comment by dcharles525** [comment]
Ok obviously @dfortner is being a little bitch and trying to piss all of you off, but anyways, let's all just abandon ship on this issue and continue on with this great project.

**Comment by stqism** [comment]
@dfoetner: your proof is incorrect and doesn't prove anything. My reason stands.

**Comment by irungentoo** [comment]
Can you keep this shitposting off my repo?

I don't see how any of this is going to improve toxcore code.

if you want to discuss this, come to our irc server: irc.tox.im port 6697 ssl. (Keep this out of our channels on freenode they are for actual support and deving.)
