### ISSUE TITLE
PGP Integration Proposal

### ISSUE THREAD

**Issue by Stebalien** [irungentoo/toxcore#1216]
# PGP Integration Proposal

The purpose of this proposal is to (a) bootstrap identity verification using an existing well established system (PGP) and (b) make it easier to connect with TOX users that you have met elsewhere.

## Story

Bob is a long time TOX user and has added his TOX address (minus the anti-spam value) as an additional UID to his PGP key.

Alice wants to call Bob. Alice and Bob have exchanged signed and/or encrypted emails before using PGP so they both have each other's PGP keys in their keyrings. 

Before she can call Bob, must create a TOX address and friend Bob. Alice creates a TOX address and adds it as a UID to her PGP key. She then sends a friend request to the TOX address listed under Bob's PGP key and includes the PGP UID containing her TOX address because he likey hasn't seen it yet.  When Bob's TOX client receives this request, it checks to see if Alice is in Bob's
keyring to help prevent spam (this TOX address doesn't include the anti-spam value). If this key is in Bob's keyring, the TOX client presents the friend request to Bob and includes any relevant information from Alice's PGP UIDs (her name, whether or not Bob trusts her, etc.). Bob could have chosen to reject Alice's friend request (or even block her PGP key) but he knows her and wants to talk to her so he accepts it.

Alice can then call Bob.

### Setup

Users optionally add their TOX addresses (minus anti-spam values) as UIDs to their PGP keys.

### Friending

1. Alice sends a friend request to Bob's TOX address (found in his PGP UID) and includes her TOX address PGP UID.
  1. Bob's client rejects the request if Alice's PGP key has been banned.
  2. Bob's client rejects the request if Alice's PGP key is not in his keyring.
  3. Bob's client optionally (configurable for people who receive a lot of spam) rejects the request if he doesn't trust Alice's key.
  4. Otherwise, Bob's client presents the request along with information about Alice from his keyring.
  5. Bob can choose to accept, reject, or ban Alice. Banning Alice bans her PGP key and blocks all future friend requests from this PGP key.
2. Alternatively, Alice sends a friend request to Bob's TOX address using the current system (including the anti-spam value instead of a PGP UID).

### Calling

No change.

## Security Note

The PGP UIDs prove that Alice and Bob claimed to control their TOX addresses at one point however, this system as proposed does not ensure that the current users of those TOX addresses currently control the associated PGP keys. This can be fixed by having Alice sign (with her key) and encrypt (with Bob's key) her friend request but this adds additional complication.

**Comment by stqism** [comment]
Sorry for the short response, but this goes against the user friendly aspect Tox aims for.

One of our primary goals has always been to make security and privacy mainstream, integrating with a poorly used public/private key system with massive keys and a large complexity for new users is the exact opposite of what we're trying to accomplish.

While the use of keyrings and signing in public key cryptology makes sense from a technical standpoint, the overwhelming factor that has to be taken above all else is how this addresses the use with end users like Grandma.

**Comment by ArchangeGabriel** [comment]
Here I will agree with @stqism (but not necessarily for the same reasons), you can simply exchange your Tox ID using email with PGP. And this avoid making the link and your identity and your Tox ID public, which for me is a high concern.

However, there is a lot of very worrying concern on a near subject (about authentication of the people your communicating with for instance) that are still unaddressed here: https://github.com/irungentoo/toxcore/issues/121.

**Comment by Stebalien** [comment]
@stqism, I'm hoping that systems like keybase will change this but that's why I said "optional". The problem that I have with Tox as-is is that it adds yet another independent identity to manage. The great thing about PGP is that it allows tying together different identities. Additionally, I'm NOT recommending that people use web of trust.

@ArchangeGabriel You can, but this isn't a user-friendly solution. To be secure, both users have to send each-other their Tox IDs and then manually add them to Tox. Other than spam, why is making one's Tox ID public a high concern (if understood the crypto docs correctly, the only sensitive part is the anti-spam tag)?

**Comment by aaannndddyyy** [comment]
while I can'T agre with @stqism due to logical inconsistence, I do do agree with @ArchangeGabriel.
if Alice and Bob already have exchanged their PGP keys (and not tox id's), they likely have sent each other e-mails too. So Alice, after creating her new tox id, sends and (encrypted) signed mail containing her tox id to Bob. Bob installs tox, and then sends Alice a FR with an PGP signed text in it. (I don't know the current limitation of length of this message, that could be the only obstacle here). Alice receives the request, checks the signature and accepts.
Many people might not like the idea of adding their tox id to their gpg keys, thought who wants is free to promote it that way. It's no security issue but a privacy issue.

**Comment by dcharles525** [comment]
I think this enhancement is going to be only covering a niche market. Tox has always aimed to be easy to use, out of the box. Users don't want to have to configure there client, they just want it to look good, work well, be hassle free, and secure. If Alice and Bob want to use PGP there are other means of communication then Tox. Its a good idea @Stebalien, trust me I would be thrilled to use this feature, but not practical for this project.

**Comment by fcore117** [comment]
I agree that i want too that Tox is easy, lightweight on libraries, CPU usage friendly, no fuzzng with PGP things. Before Tox there was only Skype that was easiest communication soft.

**Comment by optimumtact** [comment]
More importantly this is a client level feature. I assume tox core implements an API to allow clients to add friend id's.

Any willing client developer could easily add the ability to add a key from a GPG keyring.

**Comment by zetok** [comment]
Heh, looks like most of points I wanted to raise were already posted, nonetheless, here's what I wrote earlier as an answer:

>I assume tox core implements an API to allow clients to add friend id's.

  yep, it does  

> Any willing client developer could easily add the ability to add a key from a GPG keyring.

  nope. first, implementation would have to be good. *Any* wouldn't be good enough.

Of course that's not an important thing here.  

What does matter, is cost of not only accepting patch, but also maintaining it. From user perspective it may not seem like much, but please think about those things: 
- adding support for anything increases number of LOC, which means that software it more prone to the bugs, including security ones, since really *a lot* of bugs can be used to exploit security.
- support for adding some ambiguous public keys already is in core. Thus you would have to ask clients' developers to provide an API for that, or some equivalent of it. 
- Tox uses ECC. Only newest release of GPG supports that. Let's not kid ourselves, out of people who use GPG (there aren't many) only very few uses newest, buggy, unstable version of GPG, which leads to another point... 
- who would use it anyway? as mentioned, there aren't many GPG users, and their number won't be really increasing, since demand for hard to use cryptography wasn't ever strong, and won't increase due to nature of people - no one wants to waste their time learning some hard stuff that you're most likely to just fuck up anyway. 
- Tox is supposed to be *easy to use*. GPG is by no means easy to use. Period. Which leads to a bit of ideological conflict. In what way exactly does supporting importing keys from GPG help? Don't say that it'll bring GPG users to Tox, since there aren't many of them anyway. Tox's goal isn't just to provide something that "technically skilled" people would be able to use, but rather something that general population can easily use. GPG causes people to think "fuck that, I've got better things to do". So how exactly adding support for importing keys from something that generally no one uses help promote and endorse using user-friendly crypto?

====

Please also note that so far there wasn't a single developer who would want some sort of GPG support in Tox. Don't you think that it means something?
(Please correct me if I'm wrong.)

**Comment by aaannndddyyy** [comment]
IMHO, we don't need PGP integration into toxcore. If somebody signs his tox id, then if the other person uses GPG as well, he can easily verify the key himself without making the process insecure, before adding the key.
What could be a worthwhile addition is a field for free text info in lookup services, like toxme.se, where you can save your hashed tox id encrypted with your GPG private key (i.e. signed). I think it already has such a field, but I'm not sure about size limitations.

**Comment by optimumtact** [comment]
nope. first, implementation would have to be good. Any wouldn't be good enough.

I was referring to them adding it to their own client, in which the quality can be as good as they like.

I'm not advocating for adding it to tox core. I'm saying this is a feature that can and should be implemented in the clients, as opposed to toxcore
