### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by concerned-user** [irungentoo/toxcore#1228]
Post removed because it contained server logs with ips.

**Comment by concerned-user** [comment]
In case this is censored again, here are the links:
Reason of Proplex quitting: http://pastie.org/9841104
Tox tracking when Proplex visits Tox websites: https://archive.today/KkSWp

**Comment by codedust** [comment]
@irungentoo Could you please clarify why those logs existed.

It's not very helpful to remove all posts containing criticism and ignore the concerns. Sadly, you missed the chance to remove doubts and/or apologise for the (possible) data leak. I understand that you are annoyed but this doesn't legitimate you to remove blog posts. (That's a kind of censorship and conflicts with the goals of the Tox Project.)

My wish: A discussion / clarification on a fact based level without arrogance and verbal slander.

Imo, we should discuss this right here so that we reach the same people who read the discussion yesterday (even if it's not toxcore related).

fyi: This doesn't mean I agree with @dfortner. I don't want to start a new flamewar but I think the whole discussion (yesterday and today) resulted in a loss of trust in the Tox Foundation.
That's something that should not have happened the way it happened and we should do our best to rebuild the lost confidence.

**Comment by Proplex** [comment]
Can you guys @irungentoo @stqism  please explain why you were tracking me, and moreover, why were you talking about resetting my DigitalOcean account?

https://archive.today/Y6LEw

```
2015-01-14 15:26:57    irungentoo    basically proplex did an email request change on his digital ocean account which means an email containing his ip got sent to david@tox.im which ended up in the catch all email
2015-01-14 15:27:21    @urras    irungentoo: Any interesting emails?
2015-01-14 15:27:22    @NikolaiToryzin    He's the only Firefox on Android user running that specific phone model with that specific version of Android.
2015-01-14 15:27:49    @NikolaiToryzin    So he's totally trackable if you wanted
2015-01-14 15:28:11    irungentoo    urras, if you want to forcefully gain access to his digital ocean account I can reset his pass
2015-01-14 15:28:18    @NikolaiToryzin    Why would Firefox on android even show the model.
2015-01-14 15:28:26    irungentoo    NikolaiToryzin, that's chrome
2015-01-14 15:28:30    irungentoo    not firefox
2015-01-14 15:28:31    @NikolaiToryzin    Shit
2015-01-14 15:28:37    @NikolaiToryzin    I hate ua strings
2015-01-14 15:28:46    @urras    irungentoo: Nah, I'm just going to text him
2015-01-14 15:29:07    irungentoo    urras, text him what?
2015-01-14 15:29:30    @urras    That his user-agent is really unique
2015-01-14 15:29:42    @urras    Also to change his digitalocean email
2015-01-14 15:29:51    @NikolaiToryzin    He can't
2015-01-14 15:29:53    irungentoo    urras, he is changing it
2015-01-14 15:29:59    @NikolaiToryzin    He's trying
2015-01-14 15:30:09    @NikolaiToryzin    But they want his personal info
2015-01-14 15:30:12    @urras    How do you guys know
2015-01-14 15:30:18    @NikolaiToryzin    Emails.
2015-01-14 15:30:22    @urras    Ah
2015-01-14 15:30:45    @urras    >NikolaiToryzin | He's trying  
2015-01-14 15:30:58    @urras    Just to be clear, "he" is Proplex right?
2015-01-14 15:31:05    @NikolaiToryzin    Yes.
```

**Comment by ReAzem** [comment]
As a long time supporter of the project, I would also like to know whats going on.

**Comment by opensourcewunder** [comment]
This is appalling. I'm honestly disgusted to see this kind of behaviour from a project that's supposed to be about helping us improve privacy.

Getting our chat out of the hands of the NSA is useless if someone else is going to be spying on it.

**Comment by CloverField** [comment]
Are you seriously making multiple accounts to shill about this issue. You
should stop pushing it and let irungentoo explain his reason for tracking
proplex.

**Comment by opensourcewunder** [comment]
@CloverField There is NO reason for it. NO REASON! Look at those chatlogs too. 

Frankly this whole affair is disgusting and you shouldn't be defending a supposedly privacy-respecting project which has been caught red-handed spying on people.

**Comment by GrayHatter** [comment]
@opensourcewunder tracking a malicious and/or disgruntled user is kinda security 101 and privacy < security

**Comment by irungentoo** [comment]
Fuck this, here's the truth.

@Proplex here used to host our wiki, repo, blog and mail. He also used to run our twitter account. You all remember how Tox had website issues starting on December 17? This is when @Proplex here shut down everything he was hosting after some disagreements. I then tried to resolve things with him and he brought everything back up a few hours after. I thought everything was solved so I signed off and went to bed, when I woke up, he was gone and everything was down. He then refused to return any of our emails and give us any backups or anything of what he was hosting. This made me and other people a bit pissed off with him at the time (Including myself). I would have had no issues or anything if he had given us a warning of a couple days if he wanted to stop hosting the website but he didn't, he just shut down everything without warning us. We brought everything back up eventually and built everything back up by using archive.org and google cache.

Because we no longer had anything from the mail server he was hosting, I set up a catch all email address (all mails to an address that didn't exist got sent to it.) so we could find out which email addresses to recreate.

One day I got emails in the catch all mailbox from a vps provider that @Proplex here had registered with the email. Since I had not heard anything from him so I was curious. His IP was in the email (it was an email about him trying to change something on his account) and since I'm curious what he was up to (I had not heard anything from the guy and he was still refusing to talk to me) I decided to search our webserver logs quickly to see if I could find something. I realized that I could find out exactly which ips he was using by using his unique android user agent which interested me greatly. It's fascinating how android devices have unique user agents that can be tracked easily.  I shared what I found to the people in #tox-secret on freenode which is a channel where most senior people that help Tox frequent. The reason it is named prolapse.txt is because proplex sounds a lot like prolapse and because most things said in #tox-secret are not serious and should stay private. People in #tox-secret say things in there that they normally would not in public. The talk about reseting his account was a bad joke, nobody did anything.

Then someone in #tox-secret @urras who is very friendly with @Proplex sent everything to him. I don't really know what happened after except that it ended up on 4chan and some trolls jumped on the occasion to use this against Tox.

This is my probably biased version of the events. I'm sorry for my stupid actions, it was not worth it.

If anyone has any questions about this, now is the time to ask them.

**Comment by optimumtact** [comment]
Just as well no one is aware of #tox_cabal then

**Comment by im-grey** [comment]
On 2015-01-19 16:47, irungentoo wrote:
> Fuck this, here's the truth.
> 
> @Proplex [1] here used to host our wiki, repo, blog and mail. He also
> used to run our twitter account. You all remember how Tox had website
> issues starting on December 17? This is when @Proplex [1] here shut
> down everything he was hosting after some disagreements. I then tried
> to resolve things with him and he brought everything back up a few
> hours after. I thought everything was solved so I signed off and went
> to bed, when I woke up, he was gone and everything was down. He then
> refused to return any of our emails and give us any backups or
> anything of what he was hosting. This made me and other people a bit
> pissed off with him at the time (Including myself). I would have had
> no issues or anything if he had given us a warning of a couple days if
> he wanted to stop hosting the website but he didn't, he just shut down
> everything without warning us. We brought everything back up
> eventually and built everything back up by using archive.org and
> google cache.
> 
> Because we no longer had anything from the mail server he was hosting,
> I set up a catch all email address (all mails to an address that
> didn't exist got sent to it.) so we could find out which email
> addresses to recreate.
> 
> One day I got emails in the catch all mailbox from a vps provider that
> @Proplex [1] here had registered with the email. Since I had not heard
> anything from him so I was curious. His IP was in the email (it was an
> email about him trying to change something on his account) and since
> I'm curious what he was up to (I had not heard anything from the guy
> and he was still refusing to talk to me) I decided to search our
> webserver logs quickly to see if I could find something. I realized
> that I could find out exactly which ips he was using by using his
> unique android user agent which interested me greatly. It's
> fascinating how android devices have unique user agents that can be
> tracked easily. I shared what I found to the people in #tox-secret on
> freenode which is a channel where most senior people that help Tox
> frequent. The reason it is named prolapse.txt is because proplex
> sounds a lot like prolapse and because most things said in #tox-secret
> are not serious and should stay private. People in #tox-secret say
> things in there that they normally would not in public. The talk about
> reseting his account was a bad joke, nobody did anything.
> 
> Then someone in #tox-secret @urras [2] who is very friendly with
> @Proplex [1] sent everything to him. I don't really know what happened
> after except that it ended up on 4chan and some trolls jumped on the
> occasion to use this against Tox.
> 
> This is my probably biased version of the events. I'm sorry for my
> stupid actions, it was not worth it.
> 
> If anyone has any questions about this, now is the time to ask them.
> 
> --
> Reply to this email directly or view it on GitHub [3].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/Proplex
> [2] https://github.com/urras
> [3] 
> https://github.com/irungentoo/toxcore/issues/1228#issuecomment-70566974

No backups or anything?
Damn. That guy sounds like a dick.

**Comment by dcharles525** [comment]
All this drama is killing the project....

**Comment by codedust** [comment]
@irungentoo Thanks for your version! Feels a lot better now.
I have only one question left: How did you know the Android user agent belongs to Proplex?


@dcharles525 I don't think so... ;)

**Comment by Proplex** [comment]
@im-grey I had given Tox backups of both the wiki and blog a few days after. The wiki was back online by then but the blog was not.

@irungentoo Perhaps you could send me the link sent to the catch-all account so I can change the email on my DigitalOcean account? Right now you're still holding it captive.

**Comment by urras** [comment]
@irungentoo,
Thanks for publicly coming clean about everything. My intent was to uphold the principles that Tox was founded on; I'm not trying to undermine the project in any way. Tox is a wonderful project, and everyone involved has worked very hard to make Tox what it is today. I want to thank all of you for staying calm and collected during this whole ordeal. In addition, I apologize for any damage to  the infrastructure or reputation of the project and community, and sincerely wish that people continue to support our development.

**Comment by aaannndddyyy** [comment]
why do you have secret channels in the first place?
Is that an open community and development model?

**Comment by hexafluoride** [comment]
kek

**Comment by GrayHatter** [comment]
@aaannndddyyy not secret anymore, but it's a good way for the lead devs to
ask questions or discuss problems without yet making them public. If
someone says acts like a dick and tries to take over control of things like
domains or mail servers, #secret channels are a good place to discuss among
a group how to do damage control and regain control of domain names, log
files, data without bothering #tox (users) or #tox-dev (coders) not to
mention keeping users who act like a douche somewhat non-defamed.

Why don't you public post everything you say? (I for one would like to read
every thing you've ever said about anything ever...)

**Comment by urras** [comment]
@GrayHatter @aaannndddyyy I made a transparency policy a while back (https://wiki.tox.im/Transparency_policy) about this.

**Comment by irungentoo** [comment]
@codedust There were only two devices that accessed the Tox website with his IP and they both tried to access his user page which didn't exist on the new wiki, one was the android device.

**Comment by stqism** [comment]
@codedust: 
Android phones like to shove a bunch of super detailed information in the UA string like exact model and version of Android.

**Comment by codedust** [comment]
> There were only two devices that accessed the Tox website **with his IP**

@irungentoo @stqism So you got that ip from IRC, I suppose. I forgot about the ip <--> user agent relation ^^. Shame on me.

**Comment by irungentoo** [comment]
@codedust you know how some sites send you emails with your ip when you do major changes to your account?

That's how I got his IP, an email like that was sent to our catch all mail address (That's where all the emails to accounts that don't exist get sent to).

**Comment by codedust** [comment]
@irungentoo Got it! ;) (He visited the tox website the same day he tried to reset his DigitalOcean account. That's why I didn't understand it in the first place.) Thanks.

**Comment by aaannndddyyy** [comment]
@GrayHatter : I don't keep logs, but I don't say anything related to open source projects in secret, so everything I ever say related to such projects is openly accessible. Only exception being passwords and such. Those don't need secret groups though. This casts a bad light on the project.

**Comment by JFreegman** [comment]
@aaannndddyyy There are innumerable legitimate reasons to have a private room. Phone numbers, passwords, real names, flight schedules etc. have been shared in that channel. There is no rule that says FOSS project developers may not have private conversations about the project - that's ridiculous. Privacy is not a bad thing. The promotion of privacy is the central theme of the project. 

The name tox-secret is a misnomer. There is nothing secret about its existence, as @urras pointed out already. Tox-private would be a better name.

**Comment by aaannndddyyy** [comment]
@JFreegman : Really? You cannot into sending a phone number in a pm? In a project whose goal is security (and not security by obscurity). Everything that is not private information should, IMHO, be public,
ALL project related discussions. 
And there is nothing ridiculous about it.
This is not about privacy.

**Comment by JFreegman** [comment]
@aaannndddyyy It's quite honestly none of your business who shares their personal information with whomever else, be it in a private IRC channel or elsewhere. It has everything to do with privacy, of which we are strong advocates. Everyone is free to communicate on their own terms, regardless of who they are, what projects they work on, what they name their IRC channels etc. This is a fundamental freedom that every human being is born with. You are not entitled to know the contents of any private conversation, and there is no argument you could make to change that simple fact.

**Comment by miua** [comment]
1) Do you really believe, as you stated in the logs, that there's nothing "wrong with keeping cash in a paypal account" and that "having a couple hundred dollars on paypal isn't a big issue"?

2) You the following sentence you said was a joke: "urras, if you want to forcefully gain access to his digital ocean account I can reset his pass". But when I asked @urras, he answered that he didn't trust you and "told Proplex to change his emails and shit right after this.". If not even the people in #tox-secret believe you are talking seriously, you might just as well be and this is all damage control.

3) No matter the reason, you still tracked (and kept tracking until being called out on it) @Proplex who used Tor but had an unique user-agent. If you yourself don't respect one's privacy and desire to be anonymous, how do you expect us to trust the Tox Foundation lead by you and @stqism ?

4) Speaking of which, @stqism tried to sneak in a copyright change in an unrelated fix the other day. https://github.com/irungentoo/toxcore/pull/1219 And even when someone sent a much better pull request, he said it was a duplicate and he would fix his https://github.com/irungentoo/toxcore/pull/1224 Why didn't he closed his and let the proper patch be merged? Sounds really shady and as if getting the copyright changed was the real cause.

5) You used to believe @stqism was harmful to the project and wanted to lower his power in the organization to practically zero, due to his issues in maintaining simple infrastructure stuff (DNS failure, website offline, etc.), the way he treated users and developers (guile fiasco, spreading FUD against uTox, etc.). However, after meeting him personally on a weekend you decided he was actually a great contributor and should indeed head the foundation. What changed? I can't see the reasoning behind leaving all criticism behind just because you thought he was a nice person? I guess there's something you aren't telling us.

6) The Tox Foundation cause @Proplex, @notadecent, @notsecure and many other developers to abandon Tox, even though they believed in its ideals. Don't you think your unethical actions have gone too far? Do you believe anyone will trust you ever again after all this?

7) How can I know you aren't still tracking Proplex, @WubTheCaptain or anyone else? I can't trust the Tox Foundation any more in light of the recent events.

8) @stqism was completely reluctant to make the foundation transparent and you didn't care. After utter pressure from the community, he came up with something passable as "transparency" for the people who look only superficially. However, as @Proplex and others pointed out, it really isn't. Dealing with money isn't something to be taken lightly and the foundation looks really shady and unprofessional when doing so. It's as if you are trying to hide how much money is being donated and how it's spent.

9) You edited the posts by @dfortner after he brought this issue up here to make him look bad, locked the issue so he couldn't comment any more and banned him from the repository so he couldn't clear up the situation. Is that how you expect to treat disagreements? Through complete censorship and destroying someone's image?

**Comment by JFreegman** [comment]
@miua Is there a reason you created a new account just to make that reply?

**Comment by miua2** [comment]
@JFreegman I am a friend of @dfortner and, as I said in the point 9 above, he's been banned from posting in the repository. So he phoned me and asked if I could post in this issue for him. As I didn't have an account, I created one. Hope this solves your curiosity. 

And I have been banned too, while writing this response to you.
Well, whatever. I did my friend's request, there you go. If you could unban him so he could talk here, that'd be great.
Bye.

**Comment by JFreegman** [comment]
@miua2 I see, thank you for clearing that up. We have had a problem with people trolling issues with sock accounts in the past, so things like that raise suspicion.

**Comment by ProMcTagonist** [comment]
@JFreegman 
dfortner was very obviously not trolling. His post was clear and to the point and @irungentoo edited it to make it look like trolling before locking the issue. It was an obvious coverup.

**Comment by aaannndddyyy** [comment]
@JFreegman then don't be surprised if your project loses credibility. You are talking about rights, which has nothing to do wit my argument. I have an idea that you will probably like: make fox closed source. The authors have the right to do that.
If you don't care about transparency, fine.

**Comment by urras** [comment]
@ProMcTagonist The main issue with @dfortner was that he commented on other Toxcore issues (at least 10), adding irrelevant comments and not being constructive. I'm sure we can unban him now, (if he wants to add his input) however.

**Comment by stqism** [comment]
@aaannndddyyy
What @irungentoo had a problem with was spamming the code libraries code bug tracker with shitty personal issues. 

Note the word code.

**Comment by aaannndddyyy** [comment]
@miua has some very valid points.

**Comment by nckjsnjsdkanjsdk** [comment]
@urras 
So he wasn't banned for "10 troll posts" (that actually weren't), but as soon as he brings up something that would concern **many** users and shows a huge wrong-doing by the Tox Foundation (tracking users, besides other things) that issue, and only it, is edited and his account banned from posting anything again?
Sounds much more like a case of cover-up and damage control.

**Comment by rektm8** [comment]
#rekt

**Comment by aaannndddyyy** [comment]
@stqism so @Proplex was spamming the code and was therefore being tracked?

**Comment by stqism** [comment]
@miua
Your post contained a lot of personal feelings and thoughts @irungentoo didn't share in public while rehashing many of the same verbage and thoughts expressed by someone who used to troll the project. 

I'd just like to state that I find this very odd.

**Comment by urras** [comment]
@nckjsnjsdkanjsdk They were *actually* troll posts.
Like, _literally_ troll posts. The 17 or so comments he made? He was literally making the same point 17 times.

**Comment by stqism** [comment]
@aaannndddyyy
What you said makes zero sense.I'm talking about him locking and editing the issues.

**Comment by nckjsnjs** [comment]
@urras and @stqism 
 So he wasn't banned for "17 troll posts", but as soon as he brings up something that would concern many users and shows a huge wrong-doing by the Tox Foundation (tracking users, besides other things) that issue, and only it, is edited and his account banned from posting anything again?
Sounds much more like a case of cover-up and damage control.

**Comment by JFreegman** [comment]
@nckjsnjsdkanjsdk @nckjsnjs Same question to you: why did you create a new account to post those replies? It's getting very hard to differentiate the real concerns with concern trolling.

**Comment by nckjsnjs** [comment]
@JFreegman they banned @miua after all those 9 concerns were raised. There's no way to communicate with this kind of censorship. I'm out. Hope @irungentoo answers the 9 real, thoughtful, concerns raised up there.

**Comment by ProMcTagonist** [comment]
Let's focus on what actions to take immediately.

Can @Proplex describe here for the record what needs to happen right now concerning the Tox Foundation and donations?

**Comment by aaannndddyyy** [comment]
@stqism, I'm sorry but what you say isn't making any sense. I say there shouldn't be secret channels and tracking of people. Your answer was that the issue with Proplex was that he spammed the actual code lib bugtracker. That does justify it?

**Comment by dubslow** [comment]
I would say that irungentoo acted a bit impulsively, but understandably so. His repository had been harassed in the past week by dfortner, who did raise some valid points but who also very clearly had the agenda of discrediting Tox to the best of his ability. So when dfortner posted things that were supposed to be private (having been leaked), he reacted. I can't really blame him, even if I disagree with some of the particulars of how it was done.

Tox has had problems with multiple account trolls before, and so when miua posted, that was immediately suspicious.

@aaannndddyyy Stqism was talking about dfortner, not Proplex. Proplex left the project, and hasn't been banned from GitHub.

@ProMcTagonist Proplex doesn't really have a say on the matter any more, not more so than everyone else. We all agree there needs to be more transparency though. Donations have been in progress for a couple of months, with half-working pages available at public URLs, though obviously those aren't being disseminated yet, since they aren't complete.

Finally, the thing that's bothering irungentoo the most is that THIS IS A CODE REPOSITORY. WHILE THE CONCERNS EXPRESSED HERE ARE VERY VALID AND NEED DISCUSSION AND ACTION, HERE IS NOT THE PLACE.

**Comment by aaannndddyyy** [comment]
The problem is the attitudes here. Whether Proplex returns or not is not the issue. The issue is how privacy and transparency were (are?) being disrespected.

**Comment by aaannndddyyy** [comment]
@dubslow: then stqism used the wrong wording as he addressed me and was therefore implying to be answering to what I wrote.

**Comment by Astonex** [comment]
@aaannndddyyy The real problem here is literally everyone posting shit here is from 4chan http://a.pomf.se/gludku.PNG

**Comment by dubslow** [comment]
I don't agree that they are being outright disrespected (except with possibly the examination of server logs, and the leaking of those examinations). It is certainly true that transparency needs improvement, but doing that right (i.e. without accidentally harming others' privacy) isn't necessarily straigtforward. Attitudes surely need improvement, but finally, this is a code repository, not a discussion board.

**Comment by ProMcTagonist** [comment]
@dubslow I asked for his input based on the fact that the poor handling of funds was what caused him, as a long-time supporter and contributor, to finally leave the project. 

Also, it's true that this is a code repository, but as long as there's no tox-policies or tox-behavior, this is the best place for community discussion.

Gratipay has an inside.gratipay.com repo for discussion of these things.

@Astonex objectively false statement

**Comment by irungentoo** [comment]
@miua I'll respond to your troll issues one by one.

1. There is nothing wrong with storing small amounts of money in a paypal account.

2. urras is right here, he can respond to that.

3. See my big post above, also he wasn't using Tor, if he had been I would not have been able to track him.

4. stq likes to be funny sometimes, I told him I would not merge it unless that was removed.

5. What the fuck?

6. my unethical actions? nice wording you have there. 

7. Who is WubTheCaptain? How can I track people? I can't magically track people over the Internet. I'm not some elite hacker from some bad movie. I can only know who visited the Tox websites.

8. We are becoming a real IRS approved charity as soon as the gov approves our request and we have a transparency page, what more do you want?

9. I over reacted by replacing it with what I did but from now on anyone that trolls or shitpost will be banned. This repo isn't for free speech, it's for getting shit done.

**Comment by urras** [comment]
@miua I honestly don't think irungentoo was serious when he made that statement

**Comment by aaannndddyyy** [comment]
@Astonex: I know some of dpfortner' posts and dislike their tone and repetition too. So banning is one thing. But tracking project members or contributors and some of the other issues raised here are not okay. I hope tox will learn from that and not only improve codewise but also wrt transparency, and treatment of contributors. In general the tone is often aggressive and that makes it a bit of an unpleasant experience from time to time.  I think too is a great thing, and all this drama could have been avoided. You know, not every user is a security expert, so many of them are guided by the impression they have. I know a good impression of the project does not guarantee security, but bad project management makes it at least likely that other things are handled badly as well. Especially tracking a user knowing that this user cares about his privacy. That is a nogo.

**Comment by aaannndddyyy** [comment]
The only recommendation I have: reread this entire issue thread and reassess the situation, thinking about what tox' goals and values are and how certain actions are perceived by others. Then think about how the situation can be improved, and tox wants to be seen and how it can best represent its goals. I know there will always be trolls. But not everything they say is always totally wrong. Feeding the trolls isnot what you should engage in. concerns should be addressed. Trolls can be banned.

**Comment by miua4** [comment]
1) Hundreds of dollars aren't a small amount. A friend of mine earns barely nothing per month and even then donated $50 to Tox, which is a huge contribution, from his perspective. How would he feel if his money was wasted because the developers held it at Paypal, that is known to close accounts under shady reasons?

2) This might be damage control after you talked to him or he really thinks that. I have no way to know, so let's forget this.

3) Read https://archive.today/Y6LEw and you will see a contradiction to that statement of yours. 

4) That wasn't funny, it was highly disrespectful. Copyright is not a joke.

5) "What the fuck?" doesn't answer anything.

6) So you wouldn't consider tracking Proplex as an "unethical action"? What about censoring people on this repository after calling you out? I'm here on behalf of @dfortner because you edited his post so he looks like a troll and banned him from commenting.

7) Knowing who visited the Tox websites, at what time, their IP, etc. is still tracking. Also, you looked and shared emails that were directed to Proplex and even held his DigitalOcean account captive.

8) That you stop accepting donations until you actually are a real IRS approved charity and that the transparent page actually shows relevant information that can be verified.

9) Fine, but let's first end up discussing these issues, please refrain from banning people, editing posts, etc. from now on.

**Comment by aaannndddyyy** [comment]
Good luck! :-)

**Comment by Proplex** [comment]
Just stopping by to repeat what I said earlier. 

@irungentoo Perhaps you could send me the link sent to the catch-all account so I can change the email on my DigitalOcean account? Right now you're still holding it captive.

You apologized for the matter but still haven't done anything to rectify it.

**Comment by irungentoo** [comment]
@miua4 
1. Most of the paypal money is in a bank account now.

2. What is wrong with you?

3. My jokes are bad taste and were aimed at the people in #tox-secret. I never though it would leak so I didn't tone down my language to not cause misunderstandings.

4. Did it make it in toxcore? no. That means it's not an issue.

5. I just don't know how to respond to such a blatant troll.

6. This is my repo and isn't somewhere you can troll all you want. I think android having unique user agents that serve no purpose is much less ethical.

7. We don't use any javascript tracking bullshit like normal websites, if you want to call keeping server logs used to debug things tracking go ahead, almost all webservers keep them. I didn't know the emails were for proplex after I read them and looked at the headers.

8. Do you see us advertising we need donations or begging for them anywhere? The donations button is at a place where people who really want to donate can find it.

9. Only if you stay in this thread.

**Comment by irungentoo** [comment]
@Proplex I'm sorry but I'm a bit busy right now. Ping me on IRC tomorrow and we can sort this out.

**Comment by miua5** [comment]
@irungentoo

1) Why if you previously said paypal was okay for "little" money? And since when? How can we be sure?

2) "What is wrong with you?" doesn't address my concern. Nice try at avoiding my question.

3) Misunderstandings in #tox-secret are just as bad as in public. Could you have lost @notadecent, @Proplex, @notsecure and others due to misunderstandings? I think it was because of more serious concerns with the foundation, but you should review your actions anyway. Misunderstandings are never welcome.

4) It gives Tox a bad image, since people thought, including @nurupo, that @stqism was serious. @stqism is the Tox Foundation leader together with you and his actions aren't professional at all. You say it was all a joke, but many will still consider it a blatant try to pass a copyright change through a supposedly okay small fix. And you say you told him to fix the copyright issue, but if you did it was privately, since in the issue tracker there's nothing of the sort. Again, I don't buy this excuses that sound like damage control.

5) "I just don't know how to respond to such a blatant troll." doesn't address my concern. Nice try at avoiding my question.

6) Android having unique user agents that serve no purpose might be much less ethical, but that doesn't mean your own actions are acceptable. You are just less unethical than Android, but still unethical. I don't even understand why you are comparing Tox actions with Android actions, but okay.

7) So we have to trust you didn't know the emails were for proplex until after you read them and looked at the headers? Well, even if we did trust you, in the end you still shared the emails with #tox-secret and others, so it doesn't matter.

8) This is from May, much before you were even close of being IRS approved, which you aren't now anyway. https://twitter.com/projecttox/status/464467034663694336 Also, having a Donation button on the website comes close to requesting donations. What's the issue with getting approved legally by the IRS and properly making transparent reports before accepting donations? This is really shady.

9) Fine.

**Comment by dcharles525** [comment]
Ok lets all just take a step back. I think this entire issue is getting out of hand. The recent increase in of drama is starting to scare some people off. 

Tox has one end goal, to replace other communication services with a plug and play, secure, and well designed replacement for all platforms. I remember just months ago Tox was on fire, qTox, uTox, and Antox were all rapidly developing into wonderful clients. Then the organization and community started a downfall where constant bickering and arguing was everywhere, 

A lot of us are programmers, and most programmers aren't the best with public relations and being the boss, we program and thats that. @irungentoo has been hammered by stupid shit, when his main job is to just program, not be an amazing CEO PR person. @stqism has been put under a shit ton of fire in the PR department when he is working for free and putting his own money in to keep Tox alive. Devs and major contributors like @Proplex (I miss you) have left or taken a break because of arguments and stupid drama.

Now Tox does need a bit of a kick start. If the organization, organized jobs, finances, and code correctly, the project could continue with great success. We need to remember the current group of Tox contributors are not being paid and work for free, so they aren't tolerant to the massive load of bullshit they have to deal with. Now if the big players in Tox will take a step back, restructure the strategy they are implementing right now, and get organized before GSOC, if this is done, the project will have a great boost. Other projects like Hemlis, Skype and Bleep are becoming a lot better as we speak (or Tox  ;D ), its up to us to put our differences aside and work together to beat our competitors. 

All in all, we need to remember what we are here for, to create a kick ass communication service. Keep on Toxing <3
