### ISSUE TITLE
Spam prevention unclear, PoW?

### ISSUE THREAD

**Issue by o-jasper** [irungentoo/toxcore#1242]
[Spam prevention](https://github.com/irungentoo/toxcore/blob/master/docs/updates/Spam-Prevention.md)... No indication why it is hard to set to that number.

Or is the number not-revealed and it has to be found by PoW? But then once you have it, you can still spam it? Or is it PoW that has to be done between every potential friend-edge, and peers only pass on a friend request once?

Also, with PoW, you're dependent on the ability to do work. What if an attacker has a lot of computing power? Possibly friend-requests are too cheap on the network for that to be cost-effective. Meaning; a PoW that is easy enough for users still prevents attackers from flooding the network.

**Comment by TheLastProject** [comment]
nospam is only to keep someone from spamming an user with friend requests, it is not related to flooding the network.

It's something that allows you to easily change part of your ID so that, if someone posts it on some online place or something related and you're receiving many friend requests, you can drop future friend requests to the spammed Tox ID automatically by "invalidating" (for friend requests) your current Tox ID.

**Comment by o-jasper** [comment]
Looks like the confusion might be my fault, sorry for that. Still, suggest noting the distinction between this and robustness of the DHT.

**Comment by GrayHatter** [comment]
closed as stale, and incomplete. 

Please define the issue better, and why in needs to be fixed
