### ISSUE TITLE
toxcore needs multiple streams for group video chat

### ISSUE THREAD

**Issue by naldir** [irungentoo/toxcore#1245]
if you want to be a big opponent for skype you should add a screencast functionality (share video screen flow)

**Comment by dubslow** [comment]
This goes on client repositories. Note that uTox already has this.

**Comment by zetok** [comment]
@dubslow not really just a client-side thing, since from what I've been told, currently toxcore does not support sending multiple video streams (e.g. from camera and desktop) at the same time

**Comment by ProMcTagonist** [comment]
So it's up to clients to composite them before sending?

**Comment by StelarCF** [comment]
I disagree, this should be in the standard, not "up to the client to composite them". Consider the fact that a composited video might be unsuited for some screens, including phones and lower resolution screens.

**Comment by CalcProgrammer1** [comment]
I agree that Tox should support multiple streams.  On Skype if you are screencasting and have your camera turned on, the other user can click back and forth between your screen and your camera (with the other feed going to a small window overlaid on the larger feed).  Compositing would restrict this behavior to only what the client has implemented.  A generic multi-channel A/V would be great since it is the least restricting and lets clients implement any multiple stream setup they desire.

**Comment by czarkoff** [comment]
FWIW I would suggest independent streams. One could want to use different codecs for video and for desktop sharing, and probably even different framerates. It would be also nice to have a separate input events stream, so that Tox could replace VNC/RDP/TeamViewer/etc. Or, alternatively, Tox could allow incapsulating something like Spice protocol.

**Comment by GrayHatter** [comment]
@irungentoo close this? this is either a client feature, or incorrectly named.

**Comment by ProMcTagonist** [comment]
Issue needs renaming and toxcore needs multiple streams

**Comment by Jeeppler** [comment]
This feature should be renamed like: toxcore needs multiple streams for group video chat

**Comment by GrayHatter** [comment]
I cant' see this as a toxcore issue, especially as you can do this client side.

**Comment by naldir** [comment]
Seriously ? Someone who wants to share both screen and webcam video would have to composite it himself ? Everyone is not a dev or a video expert
