### ISSUE TITLE
Add Authentication to prevent MITM

### ISSUE THREAD

**Issue by aaannndddyyy** [irungentoo/toxcore#1271]
Users can get other users' tox id (tid) from untrusted sources, like toxme.se. This gives an attacker the possibility to mount an mitm or usk attack
If they know the person already they can easily have a shared secret or anything else only the two of them know. 

I suggest you implement either socialist millionaire or ZRTP or HMQV or a simple zero-knowledge authentication code:
Alice, who wants to authenticate Bob, sends Bob a long random nonce (and possibly a challenge question) in an authenticated and encrypted message. Bob then receives that nonce and uses it together with the secret to compute a code:

authCode = HMAC( [secret XOR Bob's pubkey XOR randomNonce] + [Alice' tid without nospam] )
where + means concatenation

The authCode is then sent to Alice in and authenticated encrypted message. 
Alice independently computes the same code and checks whether the tow are identical. 
If they are, Bob is now authenticated to Alice. If not, neither has learned anything about the secret.

Same procedure now with a different nonce and swapped roles, and Bob authenticates Alice.

That's it.

If there is a MITM:
Eve receives the encrypted answer from Bob, decrypts it and obtains the authCode.
Since she cannot reverse the hash, she cannot obtain the secret and hence cannot bind it to her keys.
She sends the authCode to Alice. (If she hasn't already given up, that is.)
Alice decrypts and checks nessage authenticity, which is, of course, valid.
Alice now computes the hash as outlined above, with what she thinks is Bob's id, but in fact is Eve's.
Since Eve's id is not the same as Bob's, the hash does not match the received authCode.
Alice knows she is MITM'd.

If Bob is not Bob, or Alice is not Alice, it will be noticed and none of them learns the secret.

This method provides an EASY way (compared to comparing fingerprints) to authenticate one another.
It relies on the difficulty of the hash algorithm and the quality of the shared secret (passphrase), and assumes that both parties have previously exchanged a secret in a secure way (they met each other, like in your banana example).
It thus closes the securitiy hole introduced with toxme.se without doing away with the convenience it offers.

Limitations:
This method does not provide a way to authenticate strangers. If you never met RMS and you find a tid which supposedly is his, you cannot use this method for authenticating him. But this is fine.
In that case you'd have to rely on PGP or other methods, which is totally fine, though, given that his mails and commits are signed that way too. And this does not require any changes to toxcore, it can be done manually.

Addition:

This scheme works equally well with in question-answer mode.
Alice asks Bob a question in authentication dialog, Bob answers.
Alice decrypts the received message in order to obtain the hash, and compares it to the hash she calculates just like above but instead of using a shared secret, she uses the expected answer.
Note, however, that shared secret is easier as you know beforehand about capital letters and such. But for friends you have not seen for long, Q&A is useful.

Does that add additional complexity?
Yes.

Is it much?
No.

More than an average non-tech user can handle?
Definitely not.

Tedious?
Not really, as it is only one click and one passphrase
and you would have to enter only once per contact.

This could be done in toxcore so that there are no incompatibilities between clients.
The actual amount of additional code is minimal.

There could be an authentication request, stating which method is used (shared secret or Q&A) and in Q&A case the question is included, in the case of shared secret, authCode is included.
The authentication reply contains authCode, calculated either from the shared secret or the answer.
Both packets will, of course, be encrypted and signed.
Full mutual authentication requires one message from each party in shared secret case, or <=2 each in Q&A mode.

**Comment by optimumtact** [comment]
How is having a shared secret any different to knowing one or the others public key?

They both require transition of some data on some other channel that is assumed to be secure.

**Comment by ArchangeGabriel** [comment]
You need to know the other’s key anyway, here you can exchange it on an insecure channel, the difference is it’s easier to share securely a secret than a ToxID: if you meet IRL, you can say “Hey, let’s add each other on Tox, will use ‘banana’ as secret, if you know the person quite well, you might ask her a quite secret question.

**Comment by aaannndddyyy** [comment]
When you have lookup services where you get the tox id of someone without meeting personally (maybe an old friend you haven't seen in quite a while). Or you lost your device and your tox id, then it is easy to install tox again and create a new tox id.
Compare otr with pgp. One is very easy to use for non-tech people, the other is considered to be hard. 
Both otr and zrtp developers think such an authentication method is a useful feature. And implementation is not hard. Neither would it add much code to the core. Therefore, nothing speaks against having two of them.

**Comment by arucard21** [comment]
The problem here is that your Tox client can verify that encrypted messages were created from the Tox client with the public key you have associated with your friend. But your Tox client can not verify if the public key it has associated with your friend is actually your friend's public key. This is the reason why it is vulnerable to MitM attacks.

The ways to fix this all seem to require some additional data transmitted over a channel that's known to be secure. The options mentioned here are:
- Manually compare the public key used by Tox with your friend's public key, as received over a channel known to be secure (e.g. ask personally face-to-face)
- Share a secret over a channel known to be secure and use the socialist millionaire (or similar) protocol in your Tox client to verify they are the same. If successful, you know that the public key Tox uses, is indeed your friend's public key.

Note that both ways have to be done manually and ultimately result in the user knowing that the public key used in Tox is your friend's actual public key. ___The benefit of the socialist millionaire (or similar) method is simply that it's easier to use.___

Alternative, automated solution:
It should also be possible to automatically verify which public key should be used for a Tox ID by having each Tox client store its Tox ID and corresponding public key in a distributed database (maybe a second DHT network) along with a signature that is generated with the corresponding private key (this is similar to a blockchain, as I understand it). Every client can verify that its own Tox ID is matched to the appropriate public key so others can be sure that that public key is correct. To remove the Tox ID from the database, the Tox client should prove that it has the corresponding private key, e.g. by providing a signed authentication code. The entry can be removed from the distributed database if the signature can be verified with the public key stored in that entry. This is of course much more difficult to implement, but it might be worth looking into as future feature.

**Comment by ArchangeGabriel** [comment]
I don’t understand the point of your alternative solution. ToxID is PublicKey ID, and that’s the thing you need to authentificate. So there is no other public/private key to sign those data with, that would be a feature like GPG over ToxID.

**Comment by arucard21** [comment]
@ArchangeGabriel I didn't know the Tox ID is the same as your public key. That does seem to make the alternative solution unnecessary.

**Comment by ArchangeGabriel** [comment]
Sure. But even if it wasn’t, how do you trust the public key? Same problem again. ;)

**Comment by arucard21** [comment]
You'd trust the public key in the distributed database, because you can verify the signature with that public key. That signature could only be created with the private key that corresponds to that public key, which means the public key must have been added to the distributed database by the user with access to both the public and private key.

**Comment by ArchangeGabriel** [comment]
No. That would make you trust that this ToxID is signed with this key, so that they are associated. But you can’t trust the public key, because you don’t know who owns the corresponding private key. You just know a priori that it’s the same person that have this ToxID, but you still don’t know who this is.

Everything here is about knowing for sure who has this ToxID/public key, by an independent mean.

**Comment by arucard21** [comment]
Yeah, i realized that after I posted my previous comment, which is when I updated it (but too late for your quick reply, unfortunately)

**Comment by ArchangeGabriel** [comment]
See that. But your latest proposal is incorrect. I can create a new ToxID, and then associate it with your name in toxme.se (since I own the private key of this ToxID). While forbidding someone else to register another nickname with you key won’t affect your security. The problem is someone else uploading the same nickname with a different ToxID.

**Comment by arucard21** [comment]
Yeah, you're correct. 

The alternative solution would only work if it were mandatory for everyone to create a name (as it would have been if Tox ID was just an ID linked to a separate public/private keypair). Then you can't use my nickname with your key because it would already be registered to my key.

**Comment by ArchangeGabriel** [comment]
Indeed. But we don’t want that, because we want public association of nickname and ToxID to be avoidable. And IMHO, that should even be mandatory and is the main reason why I can’t use Tox normally (or any similar soft I think)…

**Comment by aaannndddyyy** [comment]
@arucard21: with you suggestion of dht and signing, even with usernames different from keys, you'd not gain much. If it is really fully distributed, you cannot even guarantee uniqueness of the human-readable names. And whatever key a dht node reuturns for your query, as long as he who upped it there also holds the priv keyfor it (easy) he can claim to be you.
If you could guarantee uniqueness of human-readable usernames (memorizable) then you need a centralized approach like all the login-to-central-database systems. And even then: you'd trust the server. It is easy for the server to mitm you with his own keys. all you know is that there is a key and the server says that key belongs to your friend, whether that is true or not.
That brings us back to the other methods mentioned before.

**Comment by arucard21** [comment]
Yeah, I didn't know if it was feasible with DHT, but I intended it more like a block chain. These are based on a shared single source of truth, so it should guarantee uniqueness. There might be other obstacles with it though, e.g. it might be too resource-intensive to implement since we wouldn't really have many miners available nor could we reward them for their mining work (as done with bitcoin).

But no point in debating a suggestion that's founded on an incorrect assumption. The main point of that comment was to emphasize the benefit of using a socialist millionaire approach.

**Comment by GrayHatter** [comment]
I don't really understand your suggestion, but from what I do understand, why should this be in toxcore instead of in a client?
