### ISSUE TITLE
tox_callback_friend_message callback gets empty message string

### ISSUE THREAD

**Issue by pedropatinho** [irungentoo/toxcore#1307]
Hi!

I am developing a python lib for toxcore (ToxPy), and while wrapping the C api callbacks I was getting blank messages from friends. I thought it were my ctypes wrapper functions, so I went to code it again in C, but found the same behavior.
I just tried the nTox in /testing, and I can confirm it happens too: blank messages!

I started to code my stuff with the old API, and nTox worked well then, so I guess it's a bug in the new_api.

Haven't dig further, but I'm willing to port toxcore to python :-).

**Comment by dubslow** [comment]
@pedropatinho Have you looked at https://github.com/aitjcize/PyTox ? It needs porting to the new API, but for the old API is basically complete.

Then again, using ctypes would increase portability... meh up to you

**Comment by pedropatinho** [comment]
@dubslow I searched for python tox, but did't find anything, so I started to build my own... Seems like PyTox is a nice port, it should be referenced in the wiki.

About the blank messages issue, one more finding: the message is there, but starts at the 5th byte. It starts with 3 NULLs (that's why it appeared empty) and the 4th byte is "something". The length parameter includes these 4 extra bytes.

**Comment by nurupo** [comment]
@pedropatinho toxcore had API changed a week ago. If toxcore with new API and toxcore with old API communicate, the new one sees messages starting with null byte(s).

**Comment by nurupo** [comment]
i.e. make sure that both the sender and receiver are using the same API versions. Preferably the new API, because it makes no sense to make python bindings for the old API, it's going away soon.
Currently only uTox and Antox (Android client) are ported to use the new API, though all the installers/binary downloads/package repository binaries of them are freezed to use the old API until more clients support new API. So if you want to have a client that supports new API, you'd need to build uTox from source.

**Comment by nurupo** [comment]
>I searched for python tox, but did't find anything, so I started to build my own... Seems like PyTox is a nice port, it should be referenced in the wiki. 

PyTox is nice, it has online documentation, tests and examples, but [it needs to be ported to the new API](https://github.com/aitjcize/PyTox/issues/42). Would be great if *someone* could port it : )

**Comment by pedropatinho** [comment]
@nurupo Oh, thanks for enlightening me. It seems I have arrived to tox at the wrong time :).

I found about tox at March 21st, and started "playing". So I arrived right in the middle of the API change!

When will the new API become "official"? Wouldn't it be good to support communication between different API clients? 

Sorry for all these questions, I'm trying to gather as much info as I can :).

**Comment by nurupo** [comment]
The new API is "official" since it got merged into the master branch. All clients are actively porting to using it. uTox and Antox are already ported, but because the network protocol changed a bit, it would be bad to release the new uTox binaries that use new API and other client binaries that still use old API -- they won't be compatible and users would be confused, just like you did. They would receive messages with nulls in them, etc.

**Comment by aitjcize** [comment]
Is there actually any project using PyTox? I felt like I'm just making PyTox for nothing .. so I didn't really have the motivation to port it to the new API...

**Comment by subliun** [comment]
@aitjcize although PyTox isn't being used in any clients, I've used PyTox for various little helper bots. I would have used it for DiceBot, if it was working at the time. I'm sure a lot of people would appreciate you keeping it updated.

**Comment by alnf** [comment]
@aitjcize Agree with @subliun, I used it when I just started to do smth with tox, cause it was easy to implement.

**Comment by zetok** [comment]
>I would have used it for DiceBot, if it was working at the time. I'm sure a lot of people would appreciate you keeping it updated. 

Yeah, sadly PyTox never worked for me, (pythong segfaulting when trying to just load av), so I couldn't use it for what I'd like to use when I would learn how to do anything more in python.

As result I've lost interest in learning python by trying to make Tox audio groupchat bot using PyTox and now I'm in a slow process of learning rust, which has bindings for old API, and even if maintainer of bindings won't port it to new API, bindings *look* simple enough to make me want to try to do it myself when I'll learn enough.


anyway, my little story isn't that important, since what really matters is that someone has been trying to use PyTox for something serious (at least it did sound like it), and… well. Sadly, PyTox shape didn't allow him for that.


Also, there is: https://github.com/toxmail/toxmail ← may not look like it, but under the hood [it's powered by PyTox](https://github.com/toxmail/toxmail/blob/master/requirements.txt#L3) (no idea why/whether this project was stalled, since it looked interesting)

@aitjcize I really think that if PyTox bindings were working, people would use them.

(sorry if what I wrote sounds a bit harsh, this is not my intention; I merely want to say that it has a lot of potential, but it has to work first…)

**Comment by grimd34th** [comment]
@aitjcize please don't discontinue pytox it is the light shining in the dark str8c world

**Comment by stal888** [comment]
@aitjcize 
![RIP mobile users](https://cloud.githubusercontent.com/assets/774591/6995511/05b24fda-db02-11e4-8e5f-3595aa5e0c44.png)

**Comment by JFreegman** [comment]
Without Pytox there is only despair.

**Comment by optimumtact** [comment]
I agree you should give up on pytox, without a guarantee of API stability or a properly documented API there is no point developing third party wrappers.

**Comment by hexafluoride** [comment]
@aitjcize 
I'm sure that the community needs PyTox. It might not see any public use currently, but Python is a very popular language for prototyping/firing things up quickly and I'm fairly certain that it will get much use in the future where people would be more interested in the non-client part of Tox(bots, syncing, etc.).

I also feel slightly inclined to complain about @irungentoo not writing protocol docs, and @Astonex pretty much "going on an angry vacation" because of that.

**Comment by mannol** [comment]
@aitjcize I recommend PyTox to a lot of people because it's written in a safe language and prevents a lot of security critical bugs. I think that maintaining PyTox is critical for tox future because of that. Please keep doing the good work.

Thank you.

**Comment by TheLastProject** [comment]
@aitjcize Seeing how Python is such a great language for beginning programmers, PyTox is what allows people, even with little programming experience, to create software working on the Tox network. It has serious value for that reason, and I have used it for a bot myself before.

**Comment by aitjcize** [comment]
Thank you guys for the support, I'm find time for it ASAP :)

**Comment by hexafluoride** [comment]
That's really nice! Good luck!

**Comment by urras** [comment]
Thank you so much @aitjcize! :+1:

**Comment by Stefan-Code** [comment]
That's awesome, @aitjcize Thanks! :smiley:

**Comment by LittleVulpix** [comment]
@aitjcize I am told that the "LoadTest" tox bot uses PyTox, so I'd also love if you could port it over to new api as the LoadTest is a great bot for my friends who use it as an infallible indication of being online (cause they only have me in their contact list sometimes)

**Comment by GrayHatter** [comment]
currently using pytox don't let it die @aitjcize 

otherwise, stale, and incomplete issue
