### ISSUE TITLE
revocation certificate

### ISSUE THREAD

**Issue by quininer** [irungentoo/toxcore#1343]
when a tox profile is stolen, modifying the profile or informing your friends won't help.
in gpg certification, you can release a revocation certificate to invalidate the whole account, preventing further malicious use.
maybe tox can learn from that.

**Comment by zetok** [comment]
Tox doesn't work like GPG, and because of that (AFAIK) it's not really feasible to make revoking certificate work properly.

If that's all, please close issue.

**Comment by quininer** [comment]
@zetok 
The realization of the revocation certificate can consider to use offline messages (not fake).
Tox really needs a way to prevent the Profile loss.

**Comment by zetok** [comment]
Offilne messaging will be an optional thing due to its design (from what it seems, implementation will be federated), and because of that I don't consider relying on it to implement cert revocation, since not every Tox may support it, and even if it will support it, user should be able to not use it because of security reasons.

AFAIK, unless I'm wrong about that?

**Comment by quininer** [comment]
@zetok 
https://wiki.tox.im/GSoC/2015/Ideas#Offline_messaging
This appears to be toxcore project, I believe that every client should support.

**Comment by zetok** [comment]
Yes, it is a toxcore project.
"Should" doesn't mean though that clients will support it, nor that it will be used by users. It's going to be an optional "feature" and should be treated as such.

From what I know, it's going to be similar to ``toxencryptsave`` - additional feature on top of ``toxcore``, not necessarily supported by all clients, and even if supported, users aren't in any way required to use it.

**Comment by quininer** [comment]
@zetok 
You mean offline messaging is optional, user receives offline messages only when it is turned on? Won't this option enabled by default?

I expected, everything from the toxcore process. Clients do not have to know the difference between offline messages and general messages.
When toxcore revocation message is received, it will revoke the corresponding Tox ID. No client involvement.

**Comment by quininer** [comment]
If offline messaging is only a optional feature, then there seems no better way to implement revocation certificate.

I hope at least offline message reception is turned on by default. :)

**Comment by zetok** [comment]
>Clients do not have to know the difference between offline messages and general messages.

Except that they do have to know, since AFAICS API for that should be different.. Unless I'm wrong, and toxcore will be heavily modified to allow that kind thing being transparent, which I doubt that will happen, given that offline messaging most likely will be less secure, and just because of that it should have different API.

>I hope at least offline message reception is turned on by default. :)

Offline messaging will most likely will be `ON` by default in clients that will support it.

Thing is, Tox stuff should be reliable, and take under consideration that there will be people who will have it turned off. In global scale that will be **a lot of people**. Because of that, revoking certs shouldn't rely on something that may or may not be available.

**Comment by quininer** [comment]
@zetok 
> given that offline messaging most likely will be less secure
Meaning that offline messages may be lost, or may be forged?
Whether the former or the latter should try to avoid.

We may need to wait until after the offline messages to achieve before we discuss this issue.
Anyway, Tox really needs a way to prevent the Profile loss.

**Comment by aaannndddyyy** [comment]
revocations could be sent just like FR. 
As to offline messages being less secure: they should have the same encryption as standard messages, and also be cryptographically authenticated. The only difference should be the duration of a "session", i.e. the time frame in which a session key is valid.
In such a scheme, in the easy approach, offline messages could only be exchanged once the two parties have had contact at at least once.

**Comment by GrayHatter** [comment]
How would you revoke a key, know that the revocation was authentic without access to the private key?

**Comment by quininer** [comment]
@GrayHatter I agree @aaannndddyyy .

**Comment by TheNain38** [comment]
@GrayHatter It would need the revocation to be created with the private and public keys?

**Comment by aaannndddyyy** [comment]
Revocation is for when somehow someone got access to your secret key, not for when you lose the key.
All that a revocation is, is a message saying that public key pk is no longer valid, signed by the cooresponding secret key. So it is not hard to do.
They should imho be treated similar to friend requests, i.e. repeatedly sending it with decreasing frequency. Contacts that have confirmed having received it need not be given the same again. 
Once a valid revocation is received, the respective contact shoul be discarded.

TheNain38 <notifications@github.com> hat geschrieben:

@GrayHatter It would need the revocation to be created with the private and public keys?

**Comment by quininer** [comment]
A better approach is to use DHT save signature revocation messages to ensure temporarily not able to receive online friends. I had hoped to achieve this through offline messages.

**Comment by aaannndddyyy** [comment]
it would be possible without storing in the DHT, but of course, the DHT version would be an enhancement/improvement.

You can also generate the revocation cert right in the beginning and store it in another place and only send it once your id got compromised, or even if you lose your secret key. Though, if you manage not to lose the revoc. cert., how do you manage to lose the secret key?

**Comment by aaannndddyyy** [comment]
phone books have a long tradition, and if it is optional, I see no big privacy concerns with iut. Ideally you'd want to make it easy to lookup tox id by name or phone number, and a bit harder to do it the other way round (reverse lookup).

The actual problem with this in a decentralized setup is, fake/malicious entries.

**Comment by TheNain38** [comment]
@aaannndddyyy This is what I suggested, when it generate the public key and the private key it could also generate the revocation cert signed with the private key and it could be encrypted with a password, and it would need you to save it elsewhere. So if you lose the private key you didn't lose the revocation cert.

**Comment by GrayHatter** [comment]
needs a better use case, also, there's no way to revoke a key without liking toxIDs together, and that's not supported yet.

**Comment by LuccoJ** [comment]
Handling compromised account seems a perfectly valid use case to me and one that centralized systems crucially tackle. If your Tox key is not *lost*, but only *compromised*, then no, you don't need to "link" ToxIDs together to achieve this.

A revocation certificate can *additionally* be useful for when you lose your key, contrary to what @aaannndddyyy said, but only if such a revocation certificate is pre-generated and stored separately (on paper and locked away, for example), which is what GPG software encourages users to do.
But a key being compromised is still the primary and crucial use case.

**Comment by aaannndddyyy** [comment]
@LuccoJ That is not contrary to what I said.
I clearly mentioned that possibility

**Comment by GrayHatter** [comment]
So how should toxcore handle this? drop the connection and refuse to ever connect to it again? Or just prompt the user? Would it need to warn the sender? What would prevent someone from using this as a DOS attack on someone?

**Comment by aaannndddyyy** [comment]
DOS? 
Your contacts already can send you messages. I fail to see how a special message that contacts can send adds significantlt to DOS potential.
 as to the question how to treat such a message: the client should be notified so that it can inform the user and not just silently remove the contaxt and leave the user wondering.
But yes, removing the contact or marking him as untrusted. Basically it is af if your authentication system and enxryption breaks down. Woukd you then want toxcore to just inform the user but go on tp allow unencrypted communication? It is not actually unencrypted, but since your contact's key was compromised, You cannot be sure you are talking with your contact and that not someone else.

**Comment by GrayHatter** [comment]
DOS as in I block you from contacting any of your friends? and then force you to start over with a new toxid thereby losing your toxme account?

But if it's as simple as marking a contact as untrusted, that's a client issue.

Closed because either you need toxcore to drop messages, edit messages (which toxcore wont do), or just need a notification on each reciving client. If it's the first 2, no bad idea needing a different issue, or the last, in which case: client issue.

Unless I'm misunderstanding what you really want?

**Comment by aaannndddyyy** [comment]
How coukd you block me from contacting my contacts and force me to start over with a new toxid??
That does not make sense.

The only way you can accomplish this is by compromising my private key. 
And I think such a conpromise is serious enough and should be handked uniformly by toxvore and not by client.
It is about security. Otherwise you coukd as well suggest toxcore shoukd only care abiut finding your contacts's ip in the dht but not encryption; clients should do the encryption

**Comment by LuccoJ** [comment]
@GrayHatter you can't send a revocation request unless you *have the key* in the first place (or a pre-generated revocation certificate). Someone who isn't you can't revoke your key for you!
That's unless they have compromised your key, in which case, you *want* it to be revoked.

**Comment by GrayHatter** [comment]
like if I borrow your computer to look something up, notice toxicon in the tray, open tox and click the untrusted/block this account button?

So that to all of your friends it looks like your profile was stolen?

**Comment by aaannndddyyy** [comment]
Seriously, if you lend your computer and give full access to your keys to someone else, you cannot be sure anymore.
Now you will say "No, because tox savefile is encrypted", but nothing prevents the client devs to lock the revokation with a password query. This could be discussed. Otoh this would make it impossible for you to revoke in case your profile qas compromised AND you forgot your pw

**Comment by LuccoJ** [comment]
@GrayHatter if you borrow my computer and get access to my user account and Tox, you could simply delete my .tox file and render my ToxID completely useless and I would have to make a new one. So this is not an attack scenario that allows you to do anything that you couldn't do before.

In any case, if this concerns you, you could easily introduce the ability to only send a revocation request after typing a password (this could be the default for password-protected .tox files).

**Comment by GrayHatter** [comment]
@LuccoJ, not silently, and not permanently if you have a backup.
