### ISSUE TITLE
Relicense to AGPL v3.0

### ISSUE THREAD

**Issue by rrooij** [irungentoo/toxcore#1346]
First of all, I think it's great that Tox chose a free software license for the project, since it's important to have a free software replacement for Skype, that respects the user's freedoms and privacy.

GPL is a great license, but there are cases where AGPL could be more desirable than GPL and I think Tox is an example for this.

What if someone used toxcore for a web application? The one who wrote the web application doesn't have to provide the source to the clients in GPL, but the person has to in AGPL. That's why I think that AGPL is a better license choice. Someone could make a web client for Tox with a lot of server side code that users can't see. It is important to see what code the server runs with a core dedicated to privacy. That's why I think that we shouldn't allow this to happen. 

However, I understand that relicensing a project involves tedious work, since all contributers should agree with the license change etc.

What do you think about this?

**Comment by ReAzem** [comment]
> However, I understand that relicensing a project involves tedious work, since all contributers should agree with the license change etc.

Nope. As far as I know, we can to AGPL without asking anyone.

I suspect core devs plan on making buisness products so they might be against this.

**Comment by rrooij** [comment]
> Nope. As far as I know, we can go AGPL without asking anyone.

Okay. That would make things even easier.

**Comment by linux-modder** [comment]
+1 for AGPL from me too makes perfect sense especially in a use-case like one mentioned

**Comment by suhr** [comment]
> Someone could make a web client for Tox with a lot of server side code that users can't see. It is important to see what code the server runs with a core dedicated to privacy.

Client-server cannot be trusted, it doesn't matter if it's source code is open or not.

**Comment by aaannndddyyy** [comment]
@aviau No, you can't just change the license, unless there is a valid clause somewhere that all contributors ceded their rights to the Tox Foundation or a main dev. 

But @suhr is right, that the license does not help with trust issues. 
You cannot know what the server really does, no matter which license.
That said, AGPL has advantages over GPL, so a change to AGPL would be nice, but it is not something I'd be very passionate about.

**Comment by hoffmabc** [comment]
We struggled with this issue as well on the licensing for OpenBazaar. We actually moved from AGPL to MIT and the reasoning was primarily around adoption of the protocol and whether or not businesses would be willing to implement it in products if they had to publish all source code. I think IP lawyers will advise businesses to not use AGPL code in my cases as I believe it is much more strict and limiting than MIT. If that's your intention than fine but it's a trade off between these two options.

**Comment by rrooij** [comment]
@aaannndddyyy 
okay, maybe you can't trust those other servers. But it would enable you to host your own server instead, if it was AGPL.

**Comment by irungentoo** [comment]
AGPL would require anyone running something on the Tox network to give out their modified toxcore/client source which in my opinion is way too much. 

What I'm concerned about is people taking toxcore and making closed source clients and distributing them which is what the GPL prevents people from doing.

**Comment by rrooij** [comment]
I'm glad that the main developers behind Tox also share the concerns about proprietary clients, but I understand that you think AGPL is a little bit too much.

However, not licensing it AGPL could make the [Embrace, Extend, Extinguish](https://en.wikipedia.org/wiki/Embrace,_extend_and_extinguish) possible. A proprietary vendor could extend the protocol and add all kind of stuff in, even functionality that can't be compatible with other clients.

**Comment by im-grey** [comment]
That was a really good point.

**Comment by ProMcTagonist** [comment]
Big companies can do EEE no matter what. They've got the money to throw at clean-room reimplementing the protocol under their own proprietary license.

**Comment by Tirifto** [comment]
> The purpose of the GNU Affero GPL is to prevent a problem that affects developers of free programs that are often used on servers.

If Tox is likely to be (possibly) used on servers, I believe that AGPL might be very helpful. 

If someone decides to re-implement the code as proprietary software, that shouldn't be a problem. The main advantages of Tox are freedom, privacy and security. These are lost when the software is proprietary, so competition should be okay.

The problem would arise if someone would make proprietary software to interact with the existing Tox network. If servers come into play here and AGPL can be of help, then I'd like to express my support for it.

Furthermore, if someone provides a Tox service, it's true that it can't be fully trusted. If my understanding of AGPL is correct, however, it would ensure that anyone can get the code and run the very same software on their own server, where it can be trusted. That way, nobody can make a SaaSS Tox service and lure users over there, which would harm the mission of Tox. 

With AGPL, people can at the very least run their own and provide alternative servers, and the code can be used as a resource to develop non-SaaSS solutions to match any new features the SaaSS one might have brougth.

I may have misunderstood something, so I'd like for someone to confirm my claims, to avoid spreading misleading informations.

**Comment by czarkoff** [comment]
As if GPL was not already overly restrictive...

**Comment by gravgun** [comment]
@czarkoff Believe me, it's a good thing. AGPL is even better in that regard.

**Comment by codedust** [comment]
The intention behind GPL is that noone can sell/redistribute modified or unmodified versions of the software under a proprietary license **without also giving the source code to the customers**. You can even *sell* software licensed unter the GPL if you also hand out its source code.
However, GPL does *not deny* using a modified version of the software for private purposes or even internally in a company. You only have to pubish your changes to the source code if you are going to redistribute the software.
That's something many people don't know about the GPL (my personal perception) and therefore think of the GPL as a very restrictive license which restricts the *right to use* the software.

**Comment by czarkoff** [comment]
The problem is that if some vendor chooses a protocol to integrate into his application, he can't use toxcore without relicensing his application under GPL. No doubt that will slow down adoption of Tox. Obviously, AGPL is yet worse, as it would also hinder using toxcore with GPLed code.

Seriously, why do you thing glibc is not GPLed or AGPLed? GNU projects don't care about freedom as in their own definition? Or maybe that "good thing" is not as good if it is used out of place? "I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail." (Abraham Maslow)

**Comment by aaannndddyyy** [comment]
@codedust : not only without giving the source, but no reliciensing at all.
Yes, you can sell it, but you must sell it under the same License (GPL v3) or under a similar Licence (GPL <3)

**Comment by codedust** [comment]
@aaannndddyyy That's what I meant by "sell software licensed unter the GPL". But thanks for the clarification! I updated my answere to be more preceise in this point.

@czarkoff You talk about vendors integrating toxcore into their proprietary software. The question is: Do we want that? My opinion is that messaging apps should always be free software. Do we want a larger adoption af Tox at the price of loosing our freedom? We already have enough non-free messaging apps. That's why Tox is built. The better approach would be writing clients for different plattforms on our own - and I think we have the power to do so. 

Btw, there is a nice article about the the decision to release glibc under LGPL instead of GPL: https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by czarkoff** [comment]
@codedust What loosing of freedom are you talking about? Toxcore is free and will remain free as long as copyright holders permit distribution of its source code with certain conditions met. Remember, projects under Apache2, revised Lucent, BSD, ISC, MIT, CC0 or in public domain are exactly as free as projects by AGPL.

Obviously, until toxcore is actually released it is too early to count adoptions. But so far Tox is nowhere close to challenging Skype and other walled IM services. Currently we have a humble chance to turn Tox into viable free alternative to such services, but even GPL is enough a barrier on this road. Of course, project will survive under AGPL, or even more restrictive license (if it existed), but if you really cared about making as much people as possible use free software for IM/VoIP, you'd rather look at LGPL or even ISC license.

**Comment by Tirifto** [comment]
@czarkoff While software under the licenses you listed are indeed as free as software licensed under GPL, GPL is much more supportive of freedom. GPL is a [copyleft](https://www.gnu.org/copyleft/) license, meaning that the software is going to stay free. BSD, MIT and CC0 are [permissive](https://en.wikipedia.org/wiki/Permissive_free_software_license) licenses, meaning that the softfware is essentially free, but anyone can just fork it and turn it into non-free software, which is something that must be prevented.

If Tox used a permissive license, Tox developers would certainly make use of free software, but it's not so certain that the same freedom would be carried over to the users, since there's no guarantee the developers would keep their software free. I agree that would, in the end, make Tox visible and attractive for more people, but it would also defeat the main aims of Tox: freedom and privacy.

Tox needs to ensure freedom and privacy, unconditionally, since it exists to give people a simple, secure and free way to communicate. Making sure it stays like that is more difficult and slow, but if we sacrifice our values for ease and popularity, we won't have those values and the project will lose it's meaning completely. Permissive licenses are okay, but they don't protect our values very well. GLP does a good job at protecting the values. AGPL would do even a better job at protecting those values, and since I think that's the top priority, I'm supportive of the switch to AGPL.

**Comment by czarkoff** [comment]
Again, how *exactly* would usage of permissive licenses harm the aims of Tox?

The aim of *freedom*, even if considered in FSF's terms, will be served completely by any client with whole range of its dependencies under free (copyleft or permissive) license. That is: Tox will be free if it will be accessible with entirely free software setup.

The aim of *privacy* will be only served by either trusted or verified top-to-bottom stack of dependencies, and even proprietary license would do if it will allow enough rights to verify privacy enforcement. Obviously, permissive or copyleft, any free license would do.

And again, both these aims are *completely* ensured by releasing sources of toxcore and *some* clients under any license allowing to (1) *study these sources* and (2) *use self-compiled binaries* derived from such sources. GPL, AGPL, any of permissive licenses or even some non-free licenses do exactly the same to these goals.

Copyleft licenses ensure that all modifications to the source by third parties remain available, which has absolutely nothing with *Tox*'s freedom. It would serve another, unrelated goal of enforcing something that FSF calls "freedom" of software in general. Noble cause, it is not a stated goal of Tox project, and I am not sure why you are so eager to sacrifice users' ability to enjoy secure and private communication to participation in that battle.

Furthermore, GPL, AGPL or whatever license can't ensure that another, proprietary implementation of *Tox protocol* will not be used. Provided, that ISVs - those organizations whom you are trying to ban from using toxcore by employing copyleft license - are exactly those who *have* resources to do that, the ultimate difference between using copyleft and permissive licenses in case of toxcore is following:

1. some ISVs will not use toxcore even if they would like to,
1. Tox protocol will not be used in applications that could broaden its acceptance otherwise, and
1. (potentially) some ISVs would ship their own, buggy, flawed and loosily compatible implementations of Tox client.

I don't see how this is not a net loss. I don't see how value of using GPL outweights the damage. I don't see how battle for software freedom in general is more important then battle for secure and private communication.

**Comment by aaannndddyyy** [comment]
permissive licenses are free, but they do not care about preserving freedom.
GPL and AGPL do that very well.
If you are worreid about adoption in nonfree applications, instead of fully permissive licenses you should rather consider Mozilla Public License.
Personally, I'd only use fully open source versions of tox, under any of these licenses.

**Comment by czarkoff** [comment]
OK, I'm done with this issue. It was worth trying though.

**Comment by Tirifto** [comment]
@czarkoff 
> Again, how exactly would usage of permissive licenses harm the aims of Tox?

Of course, permissive licenses don't *directly* harm Tox. They just don't prevent others from doing something that does; at least not as much as copyleft does.

> Copyleft licenses ensure that all modifications to the source by third parties remain available, which has absolutely nothing with Tox's freedom. It would serve another, unrelated goal of enforcing something that FSF calls "freedom" of software in general. Noble cause, it is not a stated goal of Tox project, and I am not sure why you are so eager to sacrifice users' ability to enjoy secure and private communication to participation in that battle.

The point is exactly that all modifications to the source by third parties remains free. My concern isn't just that Tox itself remains free; my concern is that the whole Tox network and people in it remain free. What if someone makes a proprietary Tox client? Does that harm Tox as a program? No, since Tox remains free. Does that harm Tox as a network and its users? Yes, since they are exposed to and may use a program that appears to be safe, but its actions cannot be verified.

The purpose is not just protecting Tox as a program, but Tox as a network, community, user-base. And yes, it is kind of similar to FSF's cause to protect general freedom, since they have several things in common. And I said nothing about users not being able to enjoy good communication. We can do a good job making something that will respect their rights and not be used for anything that wouldn't respect them, without losing usability.

I'm saying we should ensure the best freedom/privacy/security first, and then make it as usable as we can. We could do it the other way around too, but then Tox wouldn't be very different from other IM and wouldn't really help peoples' communication.

> OK, I'm done with this issue. It was worth trying though.

You have provided valuable input for the discussion.

**Comment by codedust** [comment]
@czarkoff
> What loosing of freedom are you talking about?

@aaannndddyyy and @Tirifto already noticed that Tox could loose its freedom when someone would build a propriatary Tox client which gets very popular (maybe because it's simply better than the clients we currently have) but does harm (intentionally or unintentionally) to its uses. This would bypass the purpose of Tox as a free and secure messaging plattform.

The GPL does not prevent someone from writing it's own implementation of toxcore but at least, it doesn't allow someone to simply use toxcore inside a propriatary programm which is much easier.

As I said, I think it's possible to reach a large adoption of Tox without the help of some vendors producing proprietary software (good examples, that this is possible: Linux (GPL), OwnCloud (AGPL), Java (GPL), Blender (GPL) and many others).

I once also thought about the GPL as a "hardcore restrictive" license that only makes software development more difficult and doesn't really provide much advantages over licenses like MIT or BSD. Later, I realized that GPL makes totally sence for privacy critical software like Tox. Secure and private communication can only be based on free software.

> OK, I'm done with this issue. It was worth trying though.

I hope we could explain our reasons why we think the GPL might be the better license for toxcore. Feel free to disagree. ;)

**Comment by Jookia** [comment]
Wow, fantastic job derailing the issue with FUD, arguments that go no where and wasting people's time.

I'm not actually sure what license Toxcore is licensed under, it's very vague. There's the COPYING file, but that doesn't specify that it's the license of Toxcore, it might as well just be a document included for fun. There's no other mentions of the license in the repository. There's talk of there being a GPL exception in a GitHub issue too, so I'm not sure what to make of it.

Even if we assume COPYING is the license for the software, section 14 of the GPLv3 says that the program must specify which license it's under or the user can pick any GPL license. So I suppose you could choose GPLv2?

There's an interview with Proplex ( https://www.fsf.org/blogs/licensing/interview-with-tox ) that has a quote "we ultimately chose GPL Version 3 in the end", though the top of the article says "The Tox core library is licensed under the terms of GNU GPL version 3, or (at your option) any later version."

So which is it? Just a GPLv3 COPYING, the program proprietary? GPLv3 COPYING, the program not specifying the version meaning it can be any GPL version? GPLv3 only, no later versions allowed? GPLv3 or later? What about the exception?

I feel we should figure out the licensing terms of Tox before anything else.

**Comment by irungentoo** [comment]
@Jookia toxcore is GPLv3+

https://github.com/irungentoo/toxcore/blob/master/toxcore/DHT.c#L9-L12

This is on top of every toxcore source file and clearly states which licence the code is under.

**Comment by Jookia** [comment]
I see, how embarrassing that I missed that! Perhaps it's because I don't have the habit of prepending license information to my source files and forgot that's how every sane project does it.

Anyhow, given the history of the AGPL and GPLv3 I wouldn't be surprised to see GPLv4 merging in the AGPL. In that case it should just be a quick update.

**Comment by rrooij** [comment]
AGPL merging into GPLv4 would be so nice.

**Comment by GrayHatter** [comment]
toxcore won't be changing to AGPL any time soon. @irungentoo can reopen this issue if he's changed his mind...
