### ISSUE TITLE
Make a project source release

### ISSUE THREAD

**Issue by anatol** [irungentoo/toxcore#1353]
Hi

Tox/uTox software getting popular among Linux Arch users and I plan to work on an official package for toxcore.

I see that toxcore does not have any official releases yet. While it is possible to clone git repo and make a package from some random commit; we (package maintainers) prefer to work with periodic released versions of software. In general it is a good idea to make a new tag every 2-6 months.

Is there any chance to make a 0.xx release? Just a tag in the git repository is enough.

The same request for other your library - filter_audio.

Thanks for this useful software!

**Comment by zetok** [comment]
>we (package maintainers) prefer to work with periodic released versions of software. In general it is a good idea to make a new tag every 2-6 months.

And keep broken / outdated version of things for few months?

One of reasons why toxcore doesn't have a proper version yet is that things simply change too fast, and there are no guarantees that they will be kept compatible. Furthermore, due to the way Tox works, people who will keep using outdated builds will experience plenty of issues sooner or later, since protocol most likely will be broken again (and again).

Even after toxcore will get to the "version" point (which shouldn't be long anyway) there will be **no** guarantee of stability / protocol compatibility.

Any version that will be older then ~week will be most likely dated anyway, given the rate at which things are changing.

The way things are being done now, packaged / build scripts by Tox simply provide usually latest recent version of latest commit, which simply works with other clients. In a case where there will be major(**!**) break in protocol / API, updates to clients provided by Tox can be withheld, until all clients are compatible with newest version, so that people would get along with updates version that is supposed to work and be compatible with other clients.

When any distro would try to package Tox stuff, they simply wouldn't be able to keep up with stuff… Your mention about months when it comes to periodic updates seems to confirm that. Additionally, there's no simple way of communicating and coordinating when things are released with people that do packaging for distros - this means that any official packaging for distros will introduce chaos and will only make it harder to develop Tox, since amount of things fixed on an even weekly basis is quite huge - thus it'll be harder to distinguish which bug reports or complaints are about something that could be a possible regression, or just outdated build from "official" distro packaging.

In case where you will want to do packaging anyway with full knowledge what it will bring, just know that this kind of stuff isn't really warmly welcomed - there were already plenty of times in the past, where people using pkgbuilds from AUR complained about things that were fixed… More of that will not be a good thing.

If you could, please don't package Tox yet. It's simply not yet ready. Even when it'll have versions.

And yes, even Arch may not be bleeding edge enough to keep Tox up-to-date in their packages. Unless you are willing to package it every day, (or on change, in case where master of toxcore / client wouldn't get an update) and somehow also keep track of breaking changes, so that you would know when to withhold packaging new stuff, and resume packaging exactly at the time where rest of builds provided by Tox will be resumed?

**Comment by vitlav** [comment]
Well, what if you will just change soname every time when it is needed by soname policy?

**Comment by zetok** [comment]
@vitlav How exactly changing something that doesn't matter would help with **all** the problems listed?

**Comment by vitlav** [comment]
@zetok When the main developer merge new_api branch like that commit
https://github.com/irungentoo/toxcore/commit/3fab80409879b925979ee1a6bb0492c69bcfb7d0
he must to change soname, it will sign about the incompatible change.

Part 3.6 says us do not make hell from libraries:
http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

It is all just a signalling about breaks in protocol / API.

**Comment by zetok** [comment]
@vitlav 
>When the main developer merge new_api branch like that commit
https://github.com/irungentoo/toxcore/commit/3fab80409879b925979ee1a6bb0492c69bcfb7d0
he must to change soname, it will sign about the incompatible change.

Yeah, I agree with that.

Semver is supposed to be introduced when #1336 will get merged.

>Part 3.6 says us do not make hell from libraries:
>http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

I've only skimmed through it, but even then, it looks like it only treats about singular system. Problem here is that Tox isn't about single instances - it is a distributed network, and library simply isn't stable enough, since it has to not only be compatible with stuff on your single instance, but more importantly, communicate with other instances - i.e. protocol compatibility. Furthermore, if I understood correctly, this treats about libraries that should be used, and ready for production, even if they have to be changed later on, to adhere to changing needs. This is not the case when it comes to toxcore - even if it works great, is all shiny and stuff, it's not yet ready for that kind of thing.

>It is all just a signalling about breaks in protocol / API.

While versioning is about that, this issue is about versioning in context of packaging, which makes it a bad idea. Now, if packaging wasn't involved, it wouldn't be a bad thing…

**Comment by suhr** [comment]
See https://github.com/irungentoo/toxcore/issues/1355.
Actually, something like `tox-0.0.1-r‹unstable version›` could be used for binary packaging. It should not be used for source-based systems like portage though.

**Comment by anarcat** [comment]
> > It is all just a signalling about breaks in protocol / API.
> 
> While versioning is about that, this issue is about versioning in context of packaging, which makes it a bad idea. Now, if packaging wasn't involved, it wouldn't be a bad thing…

well, just ignore the packaging issue then. make releases respecting semver and packagers will deal with the rest.

not having proper version numbers, even in an alpha, makes this project look way more immature than it actually is.

http://www.catb.org/esr/writings/homesteading/cathedral-bazaar/ar01s04.html

**Comment by Beep6581** [comment]
"I'm waiting the first release since they are in pre alpha"
"I'll take this when they do their first release"
https://bugs.gentoo.org/show_bug.cgi?id=478874

**Comment by zetok** [comment]
@Beep6581 https://github.com/gentoo/gentoo/pull/301

**Comment by GrayHatter** [comment]
toxcore is in community for arch
