### ISSUE TITLE
Firefox OS?

### ISSUE THREAD

**Issue by Thatoo** [irungentoo/toxcore#1363]
Is there a project to release Tox on Firefox OS?

I tried Tox between an Ubuntu computer and a OXS computer and the sound was just excellent!
Video were not working but the sound was so great!
Will sound call come on android devices too?

Thanks all for your work!

**Comment by codedust** [comment]
Since Firefox OS only supports WebApps written in HTML/CSS/JavaScript, Tox will probably not come to Firefox OS in the near feature. Firefox OS does not support running native C code. However, there are some options to bring Tox to Firefox OS somewhen in the future:

1) Port toxcore to Javascript
2) Use [Emscripten](https://kripken.github.io/emscripten-site/) and try to compile toxcore from C to JS
3) Run toxcore server-side and connect to the server via WebApp

The third version would be the worst in terms of privacy (because we would have to trust the server); but it would also be the most promising solution for the short-term. Ideally one would run the server by her-/himself. Some solutions for 3) already exist:

- [saneki/Xotic](saneki/Xotic) - seems outdated atm
- [codedust/WebTox](codedust/WebTox) - not outdated, but lacks of many essential features

**Comment by Thatoo** [comment]
Thank you for this complete answer. I hope some dev will read it and have the will to start this project.

**Comment by bogusabuser** [comment]
Building toxcore with emscripten should be fairly easy since libsodium already has an [emscripten build](https://github.com/jedisct1/libsodium.js), right?
Does toxcore depend on any other libraries?
If not - you should seriously consider a pure JavaScript toxcore, it will open a lot of doors!

**Comment by GrayHatter** [comment]
can JS open network sockets?

**Comment by Jeeppler** [comment]
@GrayHatter Firefox OS provides more API's, than normal JavaScript has.

**Comment by bogusabuser** [comment]
As @Jeeppler mentioned Firefox OS provides alot more than what is defined in W3C. Here is an overview of all Firefox OS JavaScript APIs https://developer.mozilla.org/en-US/Apps/Reference
And here's the TCP API https://developer.mozilla.org/en-US/docs/Web/API/TCPSocket
I know Tox prefers UDP but it can also work over TCP, correct?
Yes, Firefox OS port of Tox would be absolutely fantastic! Actually at the moment there is no real messaging application for Firefox OS at all. I have the LG Fx0 (a super cool devince) but I can't really do any messaging, Loqui IM just doesn't work.

**Comment by Jeeppler** [comment]
I would be happy if mozilla would build in Tox into Firefox OS.

**Comment by GrayHatter** [comment]
@anyone wanna try to get toxcore to compile with emscripten?

**Comment by GrayHatter** [comment]
stale, and not really a toxcore issue. If you try to compile with emscripten and run into errors, you can open issues for those.
