### ISSUE TITLE
  // , What format is the tox_save.tox file stored in? 

### ISSUE THREAD

**Issue by v6** [irungentoo/toxcore#1369]
// , 

Specifically, I am looking for a way to start working up some Python 3 or Elixir code open and access the `tox_save.tox` file for the Tox network client `μTox`. 

It looks like it could be an encrypted sqlite file, but does anyone know the format for sure?

**Comment by Impyy** [comment]
It's a binary format that isn't very well documented. If you're interested in helping to document it,  [load_state in util.c](https://github.com/irungentoo/toxcore/blob/5ea703c844b12e86702c35b53b0b798fe5f86634/toxcore/util.c#L117) is a good place to start.

**Comment by v6** [comment]
// , Why, oh why, does tox core use a binary format? 

I mean, I read this: http://www.cs.umd.edu/class/sum2003/cmsc311/Notes/BitOp/asciiBin.html

But it doesn't seem like a binary format would really improve speed, and space doesn't seem to be much of a concern. 

Could something more standard, like the dht.dat or resume.dat files of many Bittorrent clients, provide the same speed advantages as a binary format without requiring special software to inspect it? 

http://forum.utorrent.com/topic/69515-decoding-a-utorrent-dhtdat-and-resumedat-file/

**Comment by zetok** [comment]
@v6
>Why, oh why, does tox core use a binary format? 

I think that it basically all comes down to binary format being easier to deal with (load/save) in C.

>Could something more standard, like the dht.dat or resume.dat files of many Bittorrent clients, provide the same speed advantages as a binary format without requiring special software to inspect it? 

No, since that's not what it's about.

**Comment by gravgun** [comment]
@v6
Text formats are not as efficient as binary files in many cases, including Tox's save files. For instance, ASCII being 7-bit, you have to drop one bit uselessly for every byte you write, plus you must constrain yourself to the range of printable characters, reducing the representation range to 95 values.
That's ~2.68 times bigger if you want to store raw binary data (which Tox is mainly comprised of because of private and public keys being non-text) using some kind of base95 encoding.
So not only it would make the save file uselessly bigger, but also be harder to encode and decode code-wise and CPU-wise: you must parse the data, wasting CPU cycles.
Maintaining a binary file, even if it poses endian-related problems (a byte swap is cheap), is more efficient.

**Comment by v6** [comment]
// , Ah, that makes sense.

However, what conditions might make it possible or shrewd to use an already
extant binary save format designed for interaction with dht based networks?

**Comment by srkunze** [comment]
@gravgun Is that not exactly what @v6 said about efficiency these days? These files are so small, it should not make any difference.

**Comment by gravgun** [comment]
@srkunze The difference indeed isn't that significant, but that's a triple downside (bigger file, bigger code, longer load/save) versus the only pro it brings, that is, being able to edit a file by hand, which *doesn't contain text data*. It's just not worth it.

**Comment by v6** [comment]
// , Do you think the use of a file format brings only the pro of "being
able to edit a file by hand*"*, Wouters Dorian? Ought it to never really "
*contain text data"? *

**Comment by srkunze** [comment]
@gravgun There are libraries (e.g. for json) which handle all the nitty-gritty details. I would only dismiss readability and usability (diff, git etc.) for a very good reason. Not saying, the change is necessary, but if you touch that format, I would love to see a json version of it. ;)

**Comment by mihhailnovik** [comment]
example how to read it in python
```
import struct
#messenger.c
MESSENGER_STATE_TYPE_NOSPAMKEYS = 1
MESSENGER_STATE_TYPE_NAME = 4
MESSENGER_STATE_TYPE_STATUSMESSAGE = 5

def process_chunk(index, state):
    if index + 8 >= len(state):
        return
    length = struct.unpack_from("<H", state, index)[0]
    new_index = index + length + 8
    data_type = struct.unpack_from("<H", state, index + 4)[0]

    if data_type == MESSENGER_STATE_TYPE_NOSPAMKEYS:
        result = str(state[index + 8:index + 8 + length]).encode('hex')
        print("nospam = {}, public_key = {}, private_key = {}".format(result[0:4],
                                                                      result[4:36],
                                                                      result[36:68]))
    if data_type == MESSENGER_STATE_TYPE_NAME:
        print("User name = {}".format(str(state[index + 8:index + 8 + length])))

    if data_type == MESSENGER_STATE_TYPE_STATUSMESSAGE:
        print("Status = {}".format(str(state[index + 8:index + 8 + length])))
    process_chunk(new_index, state)

tox_save = open('/tmp/tox_save.tox', 'rb').read()
process_chunk(8, tox_save)
```

**Comment by emdee-is** [comment]
I can't see any sane reason to use a binary format  over something with lots of library support like JSON or YAML, but I suspect it is because it contains secret keys, so the hope was security-through-obscurity. I think that's a big mistake because keys should all be handled by a keymanager. If Tox is to be used in corporate environments, this will be a requirement.

I've started a profile reader in Python: <https://git.plastiras.org/emdee/tox_profile> It is an extension of @mihhailnovik code from a posting of his on stackoverflow.
