### ISSUE TITLE
Average dispatch free_slots to every File_Transfers 

### ISSUE THREAD

**Issue by kitech** [irungentoo/toxcore#1382]
currently, if i transfer multiple file to one friend, only one file has speed, others like paused speed.

i think if one want transfer a file more quickly, they can pause others.

is this possible average all file transfer speed with one friend?

i find the code in Messager.c: do_reqchunk_filecb,  maybe  the inner while loop can drop.

**Comment by jf99** [comment]
The way multiple file transfers are currently handled is perfect, imo. In fact, when I realised, tox was automatically pausing queued file transfers, I thought: "Wow, that's clever. Wish other messengers would do that the same way."

Because you can't do anything with many incomplete files. But only some complete files might already be useful (= better than not a single file). So tox should transfer the files one after another instead of parallel. Also, writing to many files in parallel causes fragmentation of your file system.

I really can't think of any reason, why tox should do parallel file transfers. So, why would you wanna do that?

**Comment by ProMcTagonist** [comment]
@jf99 people are confused because this deliberate pausing isn't displayed in the interface; it just looks like they've stalled. Issues should be opened on client repos.

**Comment by kitech** [comment]
yes, you are right in that case. so for me, i'm build robot for data channels base on tox file api, maybe help me find right way.
thanks

**Comment by GrayHatter** [comment]
non descriptive issue. please describe the issue better, and the needed solution.
