### ISSUE TITLE
librtmp1 from repository breaks Steam and possibly other packages on Ubuntu 15.10 x64

### ISSUE THREAD

**Issue by nazar-pc** [irungentoo/toxcore#1402]
Why `librtmp1`, `libssh-gcrypt-4` and other not tox-specific packages present in repository?
They should not be there since there are already such packages in stock Ubuntu reposoitory.

**Comment by nurupo** [comment]
>Why librtmp1, libssh-gcrypt-4 and other not tox-specific packages present in repository?

Don't think someone would bother putting them in there if they weren't needed for something. Would need to ask @tux3 to know for sure though. For example, I see that 14.04 LTS and 14.10 (discontinued as of August, but was relevant when that packages were created) don't have those packages or have only one of them.

The issue you are having is related to the fact that the current package repository doesn't make any distinction between different versions of Ubuntu or other .deb-based distro. I heard that since the current package repository maintainer, @tux3, has hard time finding free time to spend on maintaining the package repository, someone will be taking over in his stead. I will try suggesting the new repo maintainer to setup a proper per-distro and per-distro-version package repository.

To explain what I mean a bit more, you can see that https://pkg.tox.chat/dists/ has just "nighty" in it, when regular package repositories use the versioned distribution names and produce packages targeting those specific distro versions, here are just a few examples: http://us.archive.ubuntu.com/ubuntu/dists/ http://ftp.us.debian.org/debian/dists/ and https://linux.dropbox.com/ubuntu/dists/ (dropbox also hosts packages for debian and fedora). So instead of having a single "nighty" that is one-fits-them-all, it would make sense to produce more ditro-version-aware packages, in which, when using Tox package repository on Ubuntu14.04 LTS, you would get those `librtmp1`, `libssh-gcrypt-4` packages from us (or they will be statically linked into Tox clients altogether), but on, say, Ubuntu 15.10, it won't provide them, using 15.10's packages instead.

**Comment by nazar-pc** [comment]
Very good idea to have different repositories for different versions of distributive.
Also old repository had special built of qTox called `qtox-unity`, it was patched to work properly in latest versions of Unity DE, so it might be put for recent Ubuntu versions instead of regular `qtox` package, because no one needs an app with broken tray icon.

**Comment by zetok** [comment]
@nazar-pc currently there are binaries available for Linux that doesn't have this problem: https://wiki.tox.chat/binaries#other_linux

**Comment by nazar-pc** [comment]
@zetok, well, using repositories MUCH more convenient that downloading each update manually, isn't it?

**Comment by zetok** [comment]
@nazar-pc yes, but I for one don't know how to setup repo, nor do I have an access to try to make one.

**Comment by GrayHatter** [comment]
stale
