### ISSUE TITLE
Add tox EQ and improve the settings of the codec.

### ISSUE THREAD

**Issue by torvn77** [irungentoo/toxcore#1404]
After half an hour of chatting with friends via headphones I first got sick ears,
and by the end of the hour, sick and head.
The reason is the high frequency distortions and harmonics.
Please add
1)higher quality codec, even though he will generate a little more traffic.

2)the EQ to filter out the muck and adjust the sound settings under the current situation.

**Comment by Nextnx** [comment]
Wrote it somewhere else also, though might belong here?.. 
I also get different noises from most of my contacts and some are high enough to be annoying in conversations. Since I have used the mumble client/server before and it filters the sound so mush better imo (very clear of noises), that I was wondering if it's possible to adjust the current filter (settings?), or if their filter could be implemented somehow?
I like the tox' core design and simpleness so this would be very nice to have a sound filter that does a superb job also.

**Comment by Jeeppler** [comment]
Have you tried it with and without audio filter?

The audio filter option is implemented in qTox and uTox, as I know and sometimes you get a better result by not using the audio filter.

**Comment by Nextnx** [comment]
Yes I've, the filter do work, though there is some noise still present and sometimes annoying enough.
A few contact are crystal clear but they have above average sound mic/setup, like myself.

**Comment by ThePreviousOne** [comment]
What Audio codec Is Tox using? I have tested the bandwidth on it and it a large one, larger than the one Mumble uses by default. Could not we implement Speex instead?

**Comment by GrayHatter** [comment]
stale, new AV came out after this issue 

you can reopen a more descriptive issue if you'd like
