### ISSUE TITLE
Feature request - Add ability to edit a sent message.

### ISSUE THREAD

**Issue by SkyzohKey** [irungentoo/toxcore#1418]
I was thinking about how Tox could be _even better_ and realized that being able to edit an already sent message could be a really nice feature :)

**PoC for simple message editing in Toxcore:**
1. The **user** right-click a message and click on "_Edit the message_".
2. The **client** emit a _broadcast packet_ with the _message_ id and the edited message.
3. The **other(s) client(s)** handle this packet and update the message via it's id.

So, is it already planed ? I think it would be really simple to code and will be an useful feature :)

**Comment by o-jasper** [comment]
Kindah worry about overcomplication of tox core. I think a solution is to separate concerns; one part is about communication,(toxcore) and the other part about interpreting.(messaging build ontop)

It is easy to code the feature, but if you look at the API, how it might be done is another callback and another function for generating it. Basically half of the suggestion of #1403 is to accept that there may be many of these. (the other half is having a way to easily connect the return value to the call)

And #1403 would aswel be used to split off the communication from the interpretation part. You'd have the tox API and the standard of the names meaning things about chat being two separate things. For instance sending a message would be under the name `"msg"` and editing a message `"edit_msg"`, specifying for each that the data contains an ID and a string. This issue would then also be out of toxcores hair.(and into the messaging-definition one)

**Comment by ciechomke** [comment]
I think it is really bad feature. Imagine somebody say something to you, edits it and he can said that "I didn't say it earlier". Feature useful on pages with comments like facebook, github but not in instant messenger. It is completly pointless.

**Comment by ProMcTagonist** [comment]
not a core issue

**Comment by GrayHatter** [comment]
@ProMcTagonist, It is actually a core issue. There is no method in core for identifying or getting a unique message. So any method a client would have to implement would break support for other clients. So it's exactly the type of thing that would be best handled in toxcore.

**Comment by GrayHatter** [comment]
@ciechomke you have a problem with the implementation, not the feature. Any client that implements it would likely (unless they are actively trying to suck) store the edit history. I.e. the original message would remain, and would be accessible to both users. 

Your friend could then claim he never said anything. But you would still be able to see the original message. And in that case the fix would be for you to get better friends. 

Skype had this feature, and it was the most useful, and the one I miss the most.

**Comment by retuxx** [comment]
> I think it is really bad feature. Imagine somebody say something to you, edits it and he can said that "I didn't say it earlier".

I agree. If someone is able to edit an already sent message, you loose the integrity of chat history.
Moreover, it increases the complexity of the code.

**Comment by klonamy** [comment]
I think that's a future for social network not a messenger

**Comment by JFreegman** [comment]
@retuxx 
>I agree. If someone is able to edit an already sent message, you loose the integrity of chat history.

The previous messages would ideally be kept, like @GrayHatter said.

@klonamy
Skype has it, and we are the "Skype replacement" after all.

I think this is a good idea, but it should be an option that only works if both clients have it enabled. In order to achieve this without desyncing the chat history you would need the client receiving the edit-request to send back an ack indicating whether or not they accepted the edit. Only if the response is positive will the requesting client actually make the edit, otherwise they discard it.

**Comment by klonamy** [comment]
@JFreegman True, but only recently. I still think, if you going to post something, think first.

**Comment by zen2** [comment]
I understand people that think edit message feature is a bad thing for integrity, complexity, ...
But there is reality and usage. I've worked a lot with skype to communicate with team mates and edit feature is not used because we don't think first. Edit feature permits:
- to fix important typo that could lead to misinterpretation (especially for langage that use accents)
- to re-arrange layout of ascii data tabulation based copy/paste (especially array data)
- to fix bad copy/paste URL
- ...

Globally the possibility to edit permits to avoid redundant fixed messages (sometimes you could fixed several time the same message to have a clean look) to keep a clean history.

As security is always a trade-off between usage and protection, to not implement this feature for security purpose is a pure paranoid point of view.

And in addition (without ask for flames war): by definition a friend is trusted so argument "your friend can tell: you didn't say it" is not serious. Do you consider someone as a friend if he lies to you ?

**Comment by o-jasper** [comment]
Regardless if the messengers should do it,(imo they should not, or at least store all versions, but then overcomplicating) IMO it shouldnt be a core issue.. Core should provide communications, and have a layer ontop of it which defines how those are used to implement a chat. (and perhaps other layers defining other things) #1403 is a suggestion to make the core flexible enough to do so.(and i basically did it, ontop of the chat [in lua here](https://github.com/o-jasper/tox_comms)) However i should read [these changes](https://github.com/irungentoo/toxcore/pull/1375), i guess. (though i'd really like a little text indicating what the intention is)

Then the issue is out of toxcore's hair. (I kindah doubt they like "discussiony" issue threads?)

See if i can poke them @irungentoo @nurupo @mannol @FullName

**Comment by GrayHatter** [comment]
@o-jasper what if core provided a method JUST to unique and identify messages? That wouldn't be core doing anything expecting enforcing a way for clients to reference messages. @irungentoo has said that tox will ALWAYS be a communication backbone, so why not add in a feature that allows for clearer communication; the ability to reference a unique message without ambiguity.

**Comment by o-jasper** [comment]
(i responded to that in #1403)

**Comment by x368** [comment]
@zen2 you say "by definition a friend is trusted" but your contacts are not by definition your friends, the argument is misdirected.

Concerning paranoia or not: a secure messenger can by definition of security not enforce features incompatible with paranoia :)

Generally speaking, It would be certainly somewhat attractive to allow modification of the messages retroactively if the user __both keeps the history and wishes it to be volatile__. :)

This adds of course a complexity cost and opens a can of worms, transforming a one-dimensional stream of data into random access one with unclear constraints both on buffering and on the modification authorization semantics.

Thus I guess this could instead go into the client interoperability specification, allowing the clients to refer to previous messages and supply modification commands by a certain syntax __in__ the messages. Then even a dumb client could possibly visualize the commands, without the need to have a history buffer or interpret them - of course if the command language is defined to be more or less human-readable.

This would
* not add any complexity to the core
* nor cause any security issues for paranoia-minded clients and users
* not force clients to add the supporting code, either for sending the editing commands or interpreting them, without causing any interoperability issues

**Comment by zen2** [comment]
@x368: I was speaking about friends/trust/paranoia as reference to precedent messages. I realize I should have use citations. Happily your answer is not a flame but construct :)

I think skype implementation is not so bad:
- permit to modify only the last message by pressing up key and display message on a light yellow background.
- keep always the last message version in log
- display a little pen icon to tell user the message have been edited on both side.

So we could do the same way but we can even for security purpose keep messages modifications in log with a kind of prefix to tell it's an edition (that we need if tox-core don't implement message edition). It's even possible to display a popup with modifications if mouse pointer move on the "pen" icon.

Example:

MSG @t1:  this is a message
[ User press up key to call back his last message an edit it ]
MSG @t2: /+ this is an edited message

**Comment by SkyzohKeyx** [comment]
>Thus I guess this could instead go into the client interoperability specification, allowing the clients to refer to previous messages and supply modification commands by a certain syntax **in** the messages.

This is a really hacky-way to do it, toxcore should handle it, it's not to the clients to make their own specs, if irungentoo said that Toxcore will stay a messaging lib, then it should support this.

**Comment by x368** [comment]
> This is a really hacky-way to do it, toxcore should handle it, it's not to the clients to make their own specs

Note that I meant nothing else than
> instead go into the __client interoperability specification__

which means that it is __not__ a client choice but common for all of them, at the same time without putting the _implementation_ into the core.

What is "hacky-wacky" with this?

Separation is good for reliability, auditability, maintainability and more. Message manipulation can be easily separated and done on a different, higher level than message passing.

Out of the top of my head I would suggest reserving a certain string in the beginning of the message (to indicate the "to be interpreted" mode), the actual command and the decimal relative number backwards (-1, -2 and so on) followed by the line delimiter and then the new version of the message.

Like

    Take the bus 2344
    ///edit -1
    Take the bus 234

This would be fully transparent for existing clients, understandable for the users even on dumb clients and even easily extensible if necessary (e.g. no problem to specify "`///delete -N`" if "`///edit -N ''`" will be deemed insufficient some day). Note that this does not impose any restrictions on the _presentation_ of the editions to the user. Easy to write a reusable tiny _safe_ "library" to parse this stuff, too.

Why put everything in the core?? It should be kept as small as possible to remain viable security-wise.

**Comment by o-jasper** [comment]
I keep referencing that other issue, but the idea of "calling a function on the other side" and a command is essentially the same. Both have a return value too. However, the "calling function on other side" has to know which the return value is, whereas a command not so much.

So perhaps it is double-effort when you have both a (non binary) data transfer protocol. Rolling them into one presumably makes the data transfer easier to understand. And an analogous binary version can still be used. (In that case I did that double effort because i implemented both.. Though my command thingy does not support tables,(its lua) and has permissions(it is too clumsy to set them..))

I.e. if the command is `:command arg1 arg2 arg3`, the client will give that a number i.e `567`, and when it returns it could say `567->data` data should be some human readable form. (better than json..) I.e.

    567->1=12532
    2=34
    3=357
    "kittens"="good"
    false=true

(again with the lua-table style, which only doesnt accept `nil` as key... Alternatively , the list-part could be identified to show it neater, start `[12532, 34, 357]`) Often of course the "computer generated commands" and what is handy for humans to command won't be the same, but it will still be handy to easily be able to review what commands went back and forth.

Perhaps if the command has no return value, it could say `567:noreturn`

**Comment by x368** [comment]
@o-jasper It looks like you treat communication as a special case of a general "remote procedure call" setup. While technically this is a totally legitimate approach, from the security point of view it is hardly a proper/safe one.

Communication is about to transfer some data and let the other side interpret it (e.g. possibly plainly ignore). The delivery involves of course a certain dialogue but it is quite special, even if it formally _could_ be described in terms RPC.

Basically, what happens at the receiver should not be of any business of the sending side, besides the fact that the data successfully arrived.

Building on the RPC concept (which has been developed for different uses - among others, tightly coupled and trusted/trusting parties) can easily become misleading. The aim of RPC is too broad and if you start there you have to steadily and consequently check and restrict the "too general" functionality, to avoid accidentally allowing too much. There is no implicit trust between the parties who communicate via Tox!

I would be very wary about relying on a general RPC framework to handle interactions in a security-sensitive context. The RPC part _is_ easy, the hard part is to consequently handle privileges. Even such high profile projects as NFSv4 which is all about RPC did not fully/properly solve this challenge.

As a comparison, the "change indication language" I suggested above is strictly one-way and places no obligations on the receiving party (not even in the specification, nor in the implementation).

**Comment by o-jasper** [comment]
Afaics the RPC part is merely about having a standard way of unpacking the data, and a standard way to respond. It *improves* security in that regard, because the unpacking bit. (this is easier in lua, in C you need a lib "to make that table"..)

Otherwise, afaics, security is entirely up to the functions that are exposed.

You could think, oh, but then you'll make a dozen of these RPC, way too readily.. Making it "hard" to form an RPC by doing it "manually" might stop you from doing it too much, but also increases the chance of a bug each time you re-implement it. I think it is better to just make sure you are careful about what calls to implement..

And i dont think what happens at the receiver is particularly the business of the other side. It might be implemented handily as just exposing functions, but it is still just unpacking the data, simply "saying stuff to each other".. And the functions exposes should be as such.

**Comment by x368** [comment]
> Making it "hard" to form an RPC by doing it "manually" might stop you from doing it too much, but also increases the chance of a bug each time you re-implement it.

This was not my point. I suggest _not_ forming anything that reminds of RPC, either in the particular case or otherwise. (IOW: If you feel that something is going to look like RPC, from my point of view this means that this "something" should be rethought. :)

In the scope of this issue I am pretty convinced that no changes in toxcore are necesary to fully implement the desired functionality in a safe, inexpensive and a non-intrusive fashion. Hence this belongs to STS not here.

The less in the core library, the more auditable and interoperable it is, as well as its alternative implementations.

(for a healthy communication-related project, especially also security related, it is important to have alternative implementations.)

**Comment by o-jasper** [comment]
> This was not my point. I suggest not forming anything that reminds of RPC, either in the particular case or otherwise. (IOW: If you feel that something is going to look like RPC, from my point of view this means that this "something" should be rethought. :)

In the end you'll always implement something "if this message comes in, do this", and that is what RPC is. So if it is so bug-prone, you better do it *once*.

**Comment by x368** [comment]
> In the end you'll always implement something "if this message comes in, do this", and that is what RPC is.

This reasoning ignores a very important difference. In RPC the _caller_ chooses what happens, an RPC call is an order to serve. In communication it is up to the _recipient_ to decide what to do with the data, _if anything_.

The difference is enormous from the security point of view. __That's why__ the "RPC thinking" and the corresponding design are dangerous.

A regrettable example of the same kind of logical error is https://github.com/Tox/Tox-STS/issues/71 / https://github.com/notsecure/uTox/issues/1126 .

Another well known historical example of the same kind of mistake is UUCP. There data transmission was implemented as a special case inside a pretty general and convenient remote operation (RPC!) framework. The generality opened for abuse and the deployments were forced to disallow _everything_ besides a strictly limited "mail transmission" operation. The UUCP problem has been learned the _hard_ way - please do not lead the Tox developers and users on that way again.

**Comment by o-jasper** [comment]
The caller has *no* power over what functions are exposed behind them. Whether the system gets fucked up is entirely up to the functions exposed. I..e notsecure/uTox#1126 exposes a function taking the alias for granted in qtox, that is not very good. The *exposed function* does something that is not quite right.

*All* it does is unpack the data, and correspond calls to their responses. There is nothing wrong with that, and is better to operate *fewer* implementations of that, than *more*..

**Comment by GrayHatter** [comment]
You guys have veered WAY off topic. You're arguing about the formatting of
sending information that's already gone/going across.

The question at hand, is whether or not toxcore should handle altering
messages. And an even simpler question is, should toxcore assign a unique
ID to messages?

**Comment by x368** [comment]
@GrayHatter Well it became almost offtopic but is relevant because the topic is about three things:

* whether the new feature is useful enough to implement it (the consensus looks like "useful and acceptable as long as it is optional on the receiving side, either by opt-in or opt-out")

* whether the feature is to be implemented as an extension of  the existing protocol (which apparently changes the core Tox protocol specification, apparently not yet existing but being written by irungentoo) or as an isolated protocol (which would change either the core Tox specification or STS)

* given the answer to the above, which part of the framework should be responsible for the implementation, either the core library or the clients

>  simpler question is, should toxcore assign a unique ID to messages?

Your question looks like you skip the second and third steps above and talk about implementation details "in toxcore".

Let's take the decisions in the right order: why not isolate the edit operations from the core messaging by defining a fully separate and fully optional protocol without touching the existing one? 

Any actual drawback?

An apparent advantage is that we would not have to introduce any new concept on the core protocol level (like "unique id") and all the necessary (optional!) new code could be separately maintained, analyzed and debugged.

**Comment by x368** [comment]
Copying from https://github.com/Tox/Tox-STS/issues/73 :

>I would like to isolate the new functionality (past message correction) from the current core protocol. 
>
>On the other side this may be not very important - if all current users are supposed to upgrade as soon as toxcore changes. This will not be the case when there are alternative Tox core protocol implementations but for the moment we have that extra freedom to break backward compatibility.
>
>My [proposal](https://github.com/irungentoo/toxcore/issues/1418#issuecomment-139792358) was motivated by ensuring full backward compatibility and this of course comes with some costs (I have to be my own opponent, for clarity).
>
>* the _encoding_ of the modifications and the corresponding _visualization_ are to coincide in corner cases (this would happen when the clients do not interpret the messages at all); this allows full compatibility with the current core protocol, leaving it untouched; nevertheless this choice is a compromise
>
>* the semantics of the user input inevitably changes (subtly, but inevitably) - the user must be aware that some rare sequences of characters may lead to different visualization ("editing of other messages") on the receiving side than verbatim; not very intrusive but negative anyway
>
>A possible cleaner solution would be to add a message metainformation field to the core protocol (and then naturally to the toxcore API). Say, if a message has zero in this meta field than the client is not supposed to do anything extra. If the field has a number, the client is supposed to somehow visualize replacement of the contents of the message _the-number_ messages ago (surely, show the new contents even if the receiving user does not allow to overwrite/hide the old one).
>
>Does this sound acceptable from your perspective? Then indeed this issue belongs to toxcore even though STS possibly should mention _how_ the clients preferably visualize retroactive editions.

**Comment by GrayHatter** [comment]
I'm going to close this as a client issue.

If you'd like to reopen this, the title needs to be something fixable, like implement unique messages to allow for message editing.
