### ISSUE TITLE
Documentation is not easily available

### ISSUE THREAD

**Issue by RomanHargrave** [irungentoo/toxcore#1425]
I am unable to find pre-assembled documentation for the toxcore api _anywhere_. This is quite frustrating.

From what I understand, it was published on the `libtoxcore.so` domain before recent incidents occurred with regards to project management.

I am trying to implement a Tox XMPP component, but doing so without documentation is not feasible. Additionally, the default autotools configuration does not seem to ouput any documentation at all whatsoever.

**Comment by suhr** [comment]
Actually, see https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h.

**Comment by RomanHargrave** [comment]
That's what I have been looking at @suhr. That being said, it would be nice to actually have that in PDF/HTML form; however neither Sphinx (the tool used to generate the now-dead documentation) nor Doxygen (the standard too that would appear to recognise this format) output meaningful documentation, and there is no configuration for either tool present in the repository.

What would ultimately be nice is a reference implementation of a client that is in itself well-documented.

**Comment by cmotc** [comment]
@RomanHargrave I'm working on figuring out a way to do exactly this(I also used libtoxcore.so extensively). I've been on a business trip all week, but I'll see what I can do about it as soon as I get back home.

**Comment by LapFox** [comment]
There is also now https://github.com/Tox-Docs/Text which covers protocol spec, but as for API implementation documentation, not sure what other resources are availible.

**Comment by Chuongv** [comment]
I believe you folks are looking for this? https://github.com/Tox/Tox-Docs/blob/master/getting_started_in_c.rst

**Comment by RomanHargrave** [comment]
@Chuongv no, while that is helpful, it is not a documentation sheet that reflects the documentation comments spread across the libtoxcore source.

**Comment by cmotc** [comment]
I missed the API documentation from the old libtoxcore.so site, so I made a hard-to-navigate replacement with doxygen using this doxyfile. https://github.com/cmotc/toxcore/blob/master/Doxyfile. I think the most useful stuff can pretty much be found on this page https://cmotc.github.io/toxcore/da/d8f/tox_8h.html, but I kinda broad-stroked it and there's probably more information than really necessary there, and it's hard to navigate because of that. I wasn't exactly sure what I should have been generating so I erred on the side of more information at the risk of being cluttered at first. Also, except for the images, it's literally exactly just the inline documentation you could get by reading the code itself. Just a very arguably more convenient way of reading it. Maybe it helps. It seems to be helping me as I try to update ratox.

**Comment by GrayHatter** [comment]
https://github.com/Tox-Docs/Text/tree/master/src_text

poorly formatted, but generally complete. Pull request needed, welcomed, and LOVED!
