### ISSUE TITLE
Ability to change port - feature request

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1481]
I think that it would be really good if there was the ability to change the port which Tox is being run on. I understand that this is something which needs to be changed in the toxcore API, and before it is changed it can't be implemented in [clients](https://github.com/tux3/qTox/issues/2581#issuecomment-162058289).

**Comment by irungentoo** [comment]
https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L441-L459

**Comment by ElLamparto** [comment]
Agreed 100%. This is very important. It would increase network efficiency and quality of connections.
At work I have some ports routed to my machine, but not the Tox one.
Also while connecting over a VPN, the Tox port is always taken by someone else and can not be used.

**Comment by iphydf** [comment]
Like irungentoo said with few words: it's already supported. You can set it when creating a new tox instance. After that, it is fixed, and that is good. Changing it after starting would decrease network efficiency and quality of connections, because all your peers will still be talking to the old port that is no longer listening. If you want to force a specific port to be used instead of a range, set the start and end port to the same value. If this port can't be bound, tox will not run.

**Comment by SeventhSonOfASeventhSon** [comment]
Oh, sorry I had been led to understand that it wasn't already implemented, but I'm glad that it is!
