### ISSUE TITLE
Stop exact duplicate messages being displayed if not by user request

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1486]
I have recently noticed that in qTox when someone sends me a message, not all of the time, but some of the time there will be some sort of connection problem or something, so it will resend the message, and I will get a duplicate message, though the sender will only see the first:

![duplicate_messages_qtox](https://cloud.githubusercontent.com/assets/11575271/11975802/692ed0d4-a969-11e5-8608-2812e2992a70.png)

I understand that currently this is hard to avoid as @ElLamparto said:

    If the ACK is lost for any reason, the message is resent. Not much to do about it.

But if a message needs to be resent can't it send some information with it that tells the qTox client that it has been resent, and then if the qTox client registers that there is another exact duplicate message already being displayed, and this is an automatic resend, and not what the user has requested, then just not to display the duplicate message?

I originally posted this bug report [here](https://github.com/tux3/qTox/issues/2726).

**Comment by quininer** [comment]
You can try to close qTnx of fake offline message.

**Comment by cebe** [comment]
would be a good idea to have some unique identifier for a message to be able to detect duplicate receives.

**Comment by LittleVulpix** [comment]
@SeventhSonOfASeventhSon what if you're trolling your friend and you're for example spamming something like "no" 5x per second. It'd kinda suck if the trolling got filtered by the requested "feature". A unique identifier for every message on the other hand sounds like too much overhead, but I don't know if there is another way to implement this. After all, what you would need is an ack of an ack... but then you'd also have to "go deeper" and implement an ack of the ack of the ack... :D Maybe something like a sequence would work though, kind of like TCP seq numbers, you know; example below:

A: <sends message, seq number 1>
B: <receives message, confirms>
A: <receives ack, marks as sent>
A: <sends message, seq number 2>
B: <receives message, confirms>
<ack gets lost>
A: <does not receive the ack, marks for resending, seq number 2 still>
B: <receives message with seq number 2>
B: "whoa whoa we already got this one... an ack got lost, probably!"
B: <re-sends the "I got message seq number 2" ack, but doesn't duplicate the message in the chat log>
A: <receives ack, marks as sent>

It'd probably be pretty simple, like the seq number could be just some wrapping unsigned short int or something, since you wouldn't likely just lose acks for 65536 messages; and if the number reaches N, both clients would just start over from 0.

Not sure if that makes sense. It does in my head at least... and it sounds simple enough. You would have to store 2 extra bytes for each contact and the message packet would have to have 2 extra bytes of data in it, but 2 bytes sound fine to me.

**Comment by ProMcTagonist** [comment]
unique numbering for messages is already requested in core to do editing

**Comment by SeventhSonOfASeventhSon** [comment]
@LittleVulpix, That is exactly what I said here:

    ...and this is an automatic resend, and not what the user has requested, then just not to display the duplicate message?

What I meant by an "automatic resend" was the the user had not "requested" to send another message which is identical, but instead it's an automated resend. I think that if a message needs to be resent it should be sent through with a flag to say that it is an *automatic* resend, and if there is already a message which is identical to it there, to just ignore it.

**Comment by Renha** [comment]
@SeventhSonOfASeventhSon 
> I think that if a message needs to be resent it should be sent through with a flag to say that it is an automatic resend, and if there is already a message which is identical to it there, to just ignore it.

Well, imagine Angelina want to send Bobby two identical messages. She sends first, and it successfully delivered. Then she sends second, and network wires alligator eats it. Then Angelina's tox client sends automatic resend, and it's delivered ok. But Bobby's client wouldn't show it - because it is automatic.

So, I'm with @ProMcTagonist here.

**Comment by SeventhSonOfASeventhSon** [comment]
@Renha: Then each message would have to have an ID number, and the automatic resend would show which ID number it is a resend of, then if I send a message and it is delivered successfully, then I sent the same message, it gets lost, and a resend is sent which is delivered successfully it will know that it is not an automatic resend of one of the already received messages.

**Comment by Renha** [comment]
@SeventhSonOfASeventhSon don't overcomplicate things. "Automatic resend" would be just same usual message, with same message ID. Same for message editing: send new message with old ID. All we need is message ID, it's silver bullet :)

**Comment by Renha** [comment]
ID could be simple counter for each contact, raised on every successfully sent message

**Comment by LuccoJ** [comment]
I agree with @Renha that the correct solution to this is a message ID. Simply checking message content and not showing if duplicate is a hack, not a solution, and will be problematic if you're sending things that contain duplicates on purpose, such as source code as multiple messages.

**Comment by GrayHatter** [comment]
The only way to handle this in core would be if we allow core to identify messages. I think an ID is the best way to go about that.

But really, get a client that doesn't do that?

**Comment by ddobrev** [comment]
Has there been an progress on this one? An Id is the only proper fix, is it so difficult to implement? There are even external libraries which can do it. https://github.com/tux3/qTox/pull/3316, which is the only change doing anything about this problem, increases the time-out before a message is sent for the second time and I don't need to tell you what a poor pseudo-solution that is.

**Comment by GrayHatter** [comment]
@ddobrev no, toxcore is still agnostic to messages. uTox supports message queuing and doesn't do this. It's only qTox that's this broken...

**Comment by ddobrev** [comment]
@GrayHatter I understand, thank you very much for your explanation. I'll raise the issue with qTox.

**Comment by SkyzohKey** [comment]
@ddobrev that's a qTox issue since uTox nor Ricin had the problem. This issue can probably closed.

**Comment by ddobrev** [comment]
@SkyzohKey is right, if handling messages is not part of the job toxcore should do, this one would better be closed.
