### ISSUE TITLE
Is it possible to call regular phones with Tox e.g. via SIP?

### ISSUE THREAD

**Issue by cirosantilli** [irungentoo/toxcore#1500]
Ring allows it: https://ring.cx/en/documentation/technical-aspects-of-ring#PJSIP

**Comment by GrayHatter** [comment]
Yes, if you wanted to create a tox to SIP/POTS app. There's no reason you couldn't do that.

**Comment by aaannndddyyy** [comment]
while it is certainly possible to have something like that, you would lose encryption and could as well use the normal phone for that call. Nowadays everyone has a phone. So it's not that tox users could not be otherwise reachable by other phone-using folks. 

The only advantage would be that maybe you could save some money on international calls, if your call goes via internet/tox to the country where the person you want to call is. 
Or that your local SIP/phone company could not tap your wire, if it goes "tox-encrypted" to some relay / tox-SIP bridge first, but, of course, then the bridge can do that.

Would definitely not be high priority, imho.

**Comment by ThePreviousOne** [comment]
@aaannndddyyy This is just my opinion, but can you really call Tox "A Skype Alternate" if you don't implement the same features (not anti-features, trying to avoid 'that' conversation)

**Comment by GrayHatter** [comment]
You can. No one uses Skype because it can call regular phones. That's a bonus feature and not one that's critical to the idea of Skype.

E.g. if Skype suddenly dropped support for A/V calls everyone would leave Skype. If Skype dropped the ability to call land lines, they'd lose **some** market share, but nothing too significant.

**Comment by LuccoJ** [comment]
Well, Skype was kinda *created* around the idea of being able to call regular phones, but then that became secondary to Internet-only communication. In any case, I don't see how Tox could replicate this feature in any sensible way, at least while maintaining any of *its* core ideas (being distributed and secure).

**Comment by cirosantilli** [comment]
It is true that this is a side feature of Ring.

And Skype's SIP is only good because they provide "SIP" phone numbers all over the world to allow you to pay for local calls on international calls IIUC.

But still, it might be a good thing to put it in, so that people can replace all use cases of Skype with it.

But I understand if you WONTFIX this :-)

**Comment by GrayHatter** [comment]
I'm only thinking this would be a better idea for a client... Just because
if we do it in core everyone has to trust it. But if we leave it to
clients, only their users have to trust it.

**Comment by ProMcTagonist** [comment]
@cirosantilli 

We can't "put it in" to Tox, because it would take dedicated servers that strip encryption and forward you into POTS. It's inherently external to a P2P project. 

@GrayHatter everyone using Tox is using a client, and most people will use one or two clients. Shunting responsibility to clients doesn't do anything for the users. We cannot and should not offer a single/a few trustworthy enterprise&trade; service(s), so we should make sure there are as many as possible when and if the community makes it clear that this is really a desired feature, similar to the way toxdns was handled with many different providers.

**Comment by LuccoJ** [comment]
I would realistically just leave this to SIP clients, which do a good job of it and there are already a number of friendly SIP providers with cheap PSTN gateways.
If Tox already used SIP internally for audio calls, you could consider including support for standard SIP accounts... that's what Ring does... but since Tox does its own separate thing, that's less feasible.

**Comment by alexeysvrv** [comment]
Each program must perform its function well. In its protocol Tox. I adhere to the philosophy of UNICS. Why the extra push for the most part are not necessary functionality?

**Comment by GrayHatter** [comment]
becasue this is a question and not a request, closed as resolved support request
