### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by bivol** [irungentoo/toxcore#1507]
“Anti-malware app id-ed a uTox connection as malicious.

The uTox Win client doesn’t:

1) inter-session-remember "network" settings (like, minimize to system
tray). It's really annoying to have to re-set these after each boot

2) use a standard interface for drop-down boxes for the "network"
settings; you click on something, and the options which appear don't
"persist" unless you hold your clicked mouse button down (I know the
designers think they're doing something really rad by being different, but
it's not rad; it's wrong)

3) inter-session-remember your "profile password." I'm sure this is by
design, but it's dumb; it means people simply won't use it. And, sure,
security's great and all, but if no one uses it, then no one has that
vaunted security.”

**Comment by Renha** [comment]
I know the users think they're doing something really rad by writing issue to wrong project, but
it's not rad; it's wrong

**Comment by ProMcTagonist** [comment]
@bivol 

Hi! Thank you for reporting. In the future, post client issues to the client repos.

You're experiencing problems with uTox, so you would make an issue at https://github.com/grayhatter/utox.

However, I can suggest in response to 2 that you switch to [qTox](https://github.com/tux3/qtox) if it's incredibly important to you, because uTox will always have a nonstandard UI, as it uses its own toolkit.

**Comment by bivol** [comment]
Sorry for this if it's not the right place.
