### ISSUE TITLE
Avatar rate limiting

### ISSUE THREAD

**Issue by Zer0-One** [irungentoo/toxcore#1524]
Clients should have the ability to rate limit the receiving of avatar data. Mobile data users are susceptible to having their bandwidth usage maxed out due to spammed avatar changes.

**Comment by LittleVulpix** [comment]
@Zer0-One Mobile users are more susceptible to having their bandwidth usage maxed out due to https://github.com/irungentoo/toxcore/issues/1501 as it can be up to 1-1.5GB of data per day. Still, good suggestion.

**Comment by LuccoJ** [comment]
I think it might be simpler to just opt out of receiving avatar data entirely, which a mobile user may not really want or care about in the first place.

**Comment by LittleVulpix** [comment]
Well, avatar should be - at most - 64kB (I think). Unless someone is literally switching avatars every second, maliciously, there should be no problem receiving 64kB from your contacts. Even if you had 50 contacts, you'd still only use ~3MB in total on avatar data, which I think is negligible.

Avatars are important for some people; if a toggle should exist, it should be a per-user toggle, just so you can block that one jerk that keeps changing his avatar to spam you with avatar data - but you just don't want to remove him from your contact list.

**Comment by nurupo** [comment]
>Clients should have the ability to rate limit the receiving of avatar data. 

@Zer0-One don't clients already have the ability to rate limit the receiving of avatar data? I thought toxcore provided a way for clients to say "no, I don't want to receive you avatar image (perhaps because I already have it cached or I rate limit avatars)".

**Comment by GrayHatter** [comment]
@Zer0-One no, this is a client issue. avatars are just file data to toxcore. The client must explicitly send, and accept avatars.

If your client wants to save data on avatars, you should either leave the data pending until you actually need it. Or just cancel the first avatar request when I client connects.

Or per @LittleVulpix's suggestion, identify buggy clients and ignore avatars from them.

If I've missed something let me know and I'll reopen this. Otherwise, closed client issue.

**Comment by nurupo** [comment]
If you care about traffic usage and what something fixed in toxcore rather than a client, I'd bring up the following issue instead of avatars:

>\<iphy\> Jfreegman: friends can spam custom packets
>\<iphy\> Jfreegman: there isn't really anything you can do to stop people from spamming you and using up your bandwidth

**Comment by LuccoJ** [comment]
Maybe that's just a very subjective view, but I say: if your friends do that to you, then get better friends.

**Comment by GrayHatter** [comment]
@LuccoJ you're not wrong, but if toxcore provides an API for abuse, is should also try to limit its damage just a little.

**Comment by nurupo** [comment]
I guess it's pretty much true about any packets, the custom friend packets are not that special. Name, status message, text, etc. There is nothing you can do to stop people from spamming any of those except removing them from the friend list. The issue is that you don't know which friend generates all that spam. Your cogent might not provide visual feedback for the custom friend packets, or a friend might be constantly changing the name to the exactly same one, so unless your client shows "X is now known as Y" every time a name is changed -- you won't even notice this.

**Comment by ProMcTagonist** [comment]
Then the client should show some indication. Information should never be dropped without asking first.
