### ISSUE TITLE
Send a message from command line.

### ISSUE THREAD

**Issue by verycrypt** [irungentoo/toxcore#1569]
I'm looking for a method or an app to do:
+ send a message from command line
+ send file from command line

e.g.,
toxsend.exe --target=XXXXXXXX --send_file=D:/a/b/c.jpg
toxsend.exe --target=YYYYYYY --send_text="Hello. Test."
toxsend --target=YYYYYYY --send_text < echo "hello."

Is there an app for this thing?

**Comment by subliun** [comment]
http://git.2f30.org/ratox/file/README.html

**Comment by SkyzohKey** [comment]
You can probably use ToxCore and write an app yourself since nothing (except Toxic maybe) exists for this. Anyway, here are some links that could be helpful:
- [Tox bot in Vala](https://github.com/RicinApp/tox-vapi/blob/master/Bot.vala)
- [Tox file bot in Python](https://github.com/ingvar1995/filebot)
- [Tox group bot in Rust](https://github.com/zetok/Lee)
- [Tox bot in C](https://github.com/JFreegman/ToxBot)

**Comment by verycrypt** [comment]
@subliun Hmm.. too bad it's unmaintained.
@SkyzohKey thanks for useful links. But these are 100% Linux codes... I'll try converting "ToxBot" code to work in Windows.

**Comment by SkyzohKey** [comment]
Vala run on Windows, Python run on Windows, Rust run on Windows, C run on Windows. Not Linux code, cross-plateform languages. ;)
