### ISSUE TITLE
[Suggestion] Local peer connection

### ISSUE THREAD

**Issue by nakadashi** [irungentoo/toxcore#1570]
https://github.com/tux3/qTox/issues/3239

**Comment by GrayHatter** [comment]
Please test and confirm it's not functional in uTox then ping me.

Or another clien of your choice.

Or describe in detail you network setup and why you believe it's not working

**Comment by GrayHatter** [comment]
stale

**Comment by asl97** [comment]
I am pretty sure this is asking for local peer discovery.
ie: without an active internet connection. eg: ad-hoc network or (afaik, much more commonly know nowadays as) hotspot without data/internet access.

to test:
1 (optional?). disconnect all connection, ie: wifi & lan
2. test to make sure there is no internet access (open a browser or use a command like nslookup)
3. open two (different) client, lets call them A and B
4. insert id from one (A) to the other (B)

result:
nothing happen, client A doesn't get the request simply because there no internet connection.

additional note:
client A will only get the request once internet connection is restore.
