### ISSUE TITLE
Port config in qTox settings

### ISSUE THREAD

**Issue by IlyaIndigo** [irungentoo/toxcore#1630]
tcp/udp ports must be changed by user via settings window in qTox.
By default must be tcp/udp ports 33445/33445, but no 443/33445, as see from link below
https://github.com/irungentoo/toxcore/blob/6114bd7f3ef1fda71e45e81f259074cf4f8e58eb/other/bootstrap_daemon/tox-bootstrapd.c#L63

**Comment by LittleVulpix** [comment]
qTox doesn't use 443. This is only for the endpoint DHT node that tox connects to, it has nothing to do with your client.

Furthermore, qtox repo is here: https://github.com/qTox/qTox

This is toxcore.

**Comment by IlyaIndigo** [comment]
@LittleVulpix That is to me for normal customer need iptables to allow only udp 33445, I understood correctly?

**Comment by LittleVulpix** [comment]
@IlyaIndigo unless you have restricted everything, you shouldn't need to allow any ports; the clients are generally resilient enough to connect even if most ports are blocked. But if you must allow a port, then yes, 33445. If you use TCP-only mode, then you need to allow 33445 @ TCP as well, but otherwise 33445 UDP should be enough. However, tox opens many connections (~300+ ) so try it and see how it works for you. For general questions, I recommend you come to the qtox/tox irc and as questions there. Much faster replies and such questions belong on IRC rather than on repo. Thanks!
