### ISSUE TITLE
Can it be anonymous?

### ISSUE THREAD

**Issue by Mattel88** [irungentoo/toxcore#1631]
I'm using qTox and I've read that we can use it over Tor and there is a Socks5 setting in there. I wonder how anonymous it is since the whole concept is relaying on p2p. I do not think p2p is anonymous because you exchange the IP when connecting.

**Comment by GrayHatter** [comment]
An IP address shouldn't be considered identifying information to anyone except your ISP, (and by proxy those with access to your ISP's information). Tox should be generally anonymous to all the other Tox peers you'll connect to. When using Tox, you do disclose your Identity + IP to your friends. But that's true of any server less system, and even some central server systems.

That said, if you need to hide your traffic from your ISP, disabling UDP, and using Tox over Tor is expected to give you that additional level of privacy from your ISP. But this shouldn't be needed in most cases.

**Comment by Mattel88** [comment]
Well I've read that you exchange your ID when adding someone on Tox. That is an issue, isn't it? I'm not sure if Tor helps then.

I do not think the same problem occurs when going with Pidgin and Tor, huh?

**Comment by GrayHatter** [comment]
You must share your ToxID with someone you wish to talk to, that's kind of the point of Tox. But if you're unable to trust the people you're talking to, you can use Tox over Tor, and the friend you're talking to will only be able to get the IP of the Tor exit node you're using. 

But if you're unable to trust the people you're talking to, you really need to be able to personally evaluate ALL of the security implications of Tox, Tor, as well as the internet in general. Because if you're unable to trust the people you talk to on Tox, then there's PLENTY of ways that person could trick you into disclosing your IP address through a method OTHER than Tox

**Comment by GrayHatter** [comment]
Clicking on a link, a tox client's auto updater, using toxme.io or other
toxme service, opening a PDF, sending an image. The list could go on and on.

**Comment by Mattel88** [comment]
Oh, okay. Wow, there is a way to get the Ip when sending an image? Never heard of it.

**Comment by SkyzohKey** [comment]
@Mattel88 a basic php script is able to do it. Just log the ip, then send an image with the correct Content-Type header and do a little url rewriting to make it looks legit. Your contact click the link, i.e.. https://domaine.tld/my-cool-cat.png and you get his IP address.

Tox is secure as long as user is smart enough to not be dumb. 🙃

**Comment by GrayHatter** [comment]
I was actually cheating with that last one. But if you take an image on antox, send that image via Tox, depending on your settings, you may have just sent your friend your current GPS location. Not you IP address sure, but could be much more damaging.

**Comment by SkyzohKey** [comment]
@grayhatter That's why I always wanted to add EXIF stripping in the TCS, but no one considered seriously the idea...

**Comment by GrayHatter** [comment]
@SkyzohKey Tox doesn't do any kind of data modification. This would be a good feature for a client that wants to cater to the paranoid. But also VERY easy to do wrong, or mistakenly fuck up data if not done correctly.

**Comment by SkyzohKey** [comment]
@GrayHatter Antox does that, Diaspora* does that, Facebook does that, is the latest a "paranoid" website ?

**Comment by Mattel88** [comment]
Do I have to worry if accepting images or files then? I thought it is secure as long as we send an image or receive it over Tox instead of an URL.

**Comment by SkyzohKey** [comment]
It's secure if you trust your contact to not bind the image file with a RAT/Spyware/Keylogger/Ransomware/etc. You cannot blame the car maker if you filled up your 4x4 with Diesel instead of Essence. The same applies on the Internet. You cannot blame the application if you got a virus by trusting any stranger there. 🙃

**Comment by GrayHatter** [comment]
@SkyzohKey is mostly right. If you stick to secure operating systems, a good client (both Tox, and image viewer camera), and remember that the person your talking to could be trying to trick you. You should be safe enough.

That said, if you take an image, and it has GPS info, if you send that over tox, it could be bad. Most camera apps that add GPS data allow you to turn that info off. 

I'm going to close this issue as it's not really a toxcore issue, just a discussion. Please feel free to open another issue (if there's a different topic), or continue discussion here. I don't mean to discourage discussion, just trying to keep things clean as well.
